# Generated by Django 6.0 on 2026-02-08 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_dmsdocument_search_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dmsdocument',
            new_name='dms_dmsdocu_created_6e626e_idx',
            old_name='dms_docum_created_8aa8bb_idx',
        ),
        migrations.RenameIndex(
            model_name='dmsdocument',
            new_name='dms_dmsdocu_title_e94c3c_idx',
            old_name='dms_docum_title_0f6ac0_idx',
        ),
        migrations.RenameIndex(
            model_name='dmsdocument',
            new_name='dms_dmsdocu_content_613c26_idx',
            old_name='dms_docum_content_6b8f0a_idx',
        ),
    ]
