# Generated by Django 6.0 on 2026-02-26 01:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, help_text='Dotted category key, e.g. "workflow.assigned"', max_length=80)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField(blank=True, default='')),
                ('target_type', models.CharField(blank=True, default='', help_text='Logical type: "document", "workflow", "contract", …', max_length=60)),
                ('target_id', models.CharField(blank=True, default='', help_text='PK of the related object (UUID string)', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('channels_delivered', models.JSONField(blank=True, default=list, help_text='List of channels that successfully delivered: ["in_app","email"]')),
                ('email_sent', models.BooleanField(default=False)),
                ('email_error', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_triggered', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='communicati_recipie_afb620_idx'), models.Index(fields=['recipient', 'category'], name='communicati_recipie_264406_idx'), models.Index(fields=['target_type', 'target_id'], name='communicati_target__76b21c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(default='*', help_text='Category key or "*" for global', max_length=80)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email')], default='email', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category', 'channel')},
            },
        ),
    ]
