# Generated by Django 6.0 on 2026-03-28 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDigest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('realtime', 'Real-time (no digest)'), ('hourly', 'Hourly Digest'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], max_length=20)),
                ('alert_ids', models.JSONField(default=list, help_text='List of Alert UUIDs included in this digest')),
                ('alert_count', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('email_sent', models.BooleanField(default=False)),
                ('email_error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_body', models.JSONField(default=dict)),
                ('request_headers', models.JSONField(default=dict)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human label, e.g. "Slack #alerts"', max_length=200)),
                ('url', models.URLField(help_text='HTTPS endpoint URL', max_length=500)),
                ('secret', models.CharField(blank=True, default='', help_text='Shared secret for HMAC-SHA256 signature header (X-Webhook-Signature)', max_length=255)),
                ('categories', models.JSONField(blank=True, default=list, help_text='List of category keys to subscribe to. Empty = all.')),
                ('custom_headers', models.JSONField(blank=True, default=dict, help_text='Extra headers sent with each webhook POST')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('auto_disable_threshold', models.PositiveIntegerField(default=10, help_text='Disable webhook after this many consecutive failures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='channels_requested',
            field=models.JSONField(blank=True, default=list, help_text='Channels requested: ["in_app", "email", "webhook"]'),
        ),
        migrations.AddField(
            model_name='alert',
            name='dedup_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Hash key for deduplication within a time window', max_length=255),
        ),
        migrations.AddField(
            model_name='alert',
            name='delivery_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('deduped', 'Deduplicated'), ('digested', 'Batched for Digest')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Auto-delete after this time (TTL for transient alerts)', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='group_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Key for grouping related alerts in UI (e.g. "document:<uuid>")', max_length=255),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alert',
            name='max_retries',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='alert',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='alertpreference',
            name='digest_frequency',
            field=models.CharField(choices=[('realtime', 'Real-time (no digest)'), ('hourly', 'Hourly Digest'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='realtime', help_text='How often to batch alerts (email only)', max_length=20),
        ),
        migrations.AddField(
            model_name='alertpreference',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, help_text='End of quiet hours (UTC). Null = no quiet hours.', null=True),
        ),
        migrations.AddField(
            model_name='alertpreference',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, help_text='Start of quiet hours (UTC). Null = no quiet hours.', null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='channels_delivered',
            field=models.JSONField(blank=True, default=list, help_text='Channels that successfully delivered: ["in_app","email"]'),
        ),
        migrations.AlterField(
            model_name='alertpreference',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('webhook', 'Webhook')], default='email', max_length=20),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['recipient', 'is_archived', '-created_at'], name='communicati_recipie_8f8f33_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['delivery_status', 'next_retry_at'], name='communicati_deliver_2e4edb_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['dedup_key', 'created_at'], name='communicati_dedup_k_73580e_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['group_key'], name='communicati_group_k_f40246_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['expires_at'], name='communicati_expires_85e61c_idx'),
        ),
        migrations.AddField(
            model_name='notificationdigest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_digests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='communications.alert'),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='communications.webhookendpoint'),
        ),
        migrations.AddIndex(
            model_name='notificationdigest',
            index=models.Index(fields=['user', 'frequency', '-created_at'], name='communicati_user_id_b999ef_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', '-created_at'], name='communicati_endpoin_6328f4_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['alert', '-created_at'], name='communicati_alert_i_b826f7_idx'),
        ),
    ]
