# Generated by Django 6.0 on 2026-02-22 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('sharing', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewerToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, help_text='Cryptographically secure URL-safe token', max_length=128, unique=True)),
                ('access_mode', models.CharField(choices=[('public', 'Public — anyone with link'), ('email_otp', 'Email OTP — verify email, no registration'), ('invite_only', 'Invite Only — accept invitation first')], default='public', max_length=20)),
                ('role', models.CharField(choices=[('viewer', 'Viewer — read-only PDF'), ('commentator', 'Commentator — can add comments')], default='viewer', max_length=20)),
                ('recipient_email', models.EmailField(blank=True, help_text='Required for email_otp and invite_only modes', max_length=254, null=True)),
                ('recipient_name', models.CharField(blank=True, help_text='Display name for the recipient', max_length=255, null=True)),
                ('invitation_sent', models.BooleanField(default=False)),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_accepted', models.BooleanField(default=False)),
                ('invitation_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('password_hash', models.CharField(blank=True, help_text='Optional password protection (bcrypt/pbkdf2 hash)', max_length=128, null=True)),
                ('max_access_count', models.PositiveIntegerField(blank=True, help_text='Max number of accesses. null = unlimited.', null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, help_text='null = never expires', null=True)),
                ('allowed_actions', models.JSONField(blank=True, default=list, help_text='List of permitted actions: "view", "download", "print", "ai_chat"')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='\n        Production-level customisation:\n        {\n            "watermark_enabled": true,\n            "watermark_text": "CONFIDENTIAL",\n            "branding_message": "Shared by Acme Legal",\n            "branding_logo_url": "https://...",\n            "theme": "light" | "dark",\n            "disable_text_selection": false,\n            "require_nda_acceptance": false,\n            "nda_text": "...",\n            "custom_css": "...",\n            "show_page_numbers": true,\n            "analytics_enabled": true,\n        }\n        ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_viewer_tokens', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='Document this token grants access to', on_delete=django.db.models.deletion.CASCADE, related_name='viewer_tokens', to='documents.document')),
                ('share', models.ForeignKey(blank=True, help_text='Optional link to parent Share record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewer_tokens', to='sharing.share')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViewerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email of the viewer (verified via OTP or invitation)', max_length=254)),
                ('session_token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, help_text='Auto-linked if email matches a registered user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewer_sessions', to=settings.AUTH_USER_MODEL)),
                ('viewer_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='viewer.viewertoken')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViewerOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('otp_hash', models.CharField(help_text='PBKDF2 hash of the 6-digit OTP', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('viewer_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='viewer.viewertoken')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViewerAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(default='view', help_text='view, download, print, ai_chat', max_length=30)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_access_logs', to='documents.document')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='viewer.viewersession')),
                ('viewer_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='viewer.viewertoken')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='viewertoken',
            index=models.Index(fields=['token'], name='viewer_view_token_9ae22a_idx'),
        ),
        migrations.AddIndex(
            model_name='viewertoken',
            index=models.Index(fields=['document', 'is_active'], name='viewer_view_documen_b8af84_idx'),
        ),
        migrations.AddIndex(
            model_name='viewertoken',
            index=models.Index(fields=['recipient_email'], name='viewer_view_recipie_37b217_idx'),
        ),
        migrations.AddIndex(
            model_name='viewertoken',
            index=models.Index(fields=['access_mode'], name='viewer_view_access__8ec6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='viewertoken',
            index=models.Index(fields=['created_by', '-created_at'], name='viewer_view_created_4806ae_idx'),
        ),
        migrations.AddIndex(
            model_name='viewersession',
            index=models.Index(fields=['session_token'], name='viewer_view_session_eefb03_idx'),
        ),
        migrations.AddIndex(
            model_name='viewersession',
            index=models.Index(fields=['viewer_token', 'email'], name='viewer_view_viewer__8a6146_idx'),
        ),
        migrations.AddIndex(
            model_name='viewerotp',
            index=models.Index(fields=['viewer_token', 'email', '-created_at'], name='viewer_view_viewer__3b0148_idx'),
        ),
        migrations.AddIndex(
            model_name='vieweraccesslog',
            index=models.Index(fields=['viewer_token', '-accessed_at'], name='viewer_view_viewer__d9ab34_idx'),
        ),
        migrations.AddIndex(
            model_name='vieweraccesslog',
            index=models.Index(fields=['document', '-accessed_at'], name='viewer_view_documen_3ee77d_idx'),
        ),
    ]
