# Generated by Django 6.0 on 2026-02-23 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '__first__'),
        ('documents', '0001_initial'),
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewerComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(help_text='UUID of the target element', max_length=255)),
                ('target_type', models.CharField(choices=[('document', 'Document'), ('section', 'Section'), ('paragraph', 'Paragraph'), ('table', 'Table'), ('image', 'Image Component')], db_index=True, default='document', help_text='Readable target type for filtering', max_length=20)),
                ('text', models.TextField(help_text='The comment text')),
                ('author_email', models.EmailField(help_text='Email of the commenter (from viewer session)', max_length=254)),
                ('author_name', models.CharField(blank=True, default='', help_text='Display name of the commenter', max_length=255)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether this comment thread has been resolved')),
                ('resolved_by', models.CharField(blank=True, default='', help_text='Who resolved this comment', max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra data: highlight range, suggested text, etc.')),
                ('content_type', models.ForeignKey(help_text='Type of the target element (Section, Paragraph, Table, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('document', models.ForeignKey(help_text='The document this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='viewer_comments', to='documents.document')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='viewer.viewercomment')),
                ('session', models.ForeignKey(blank=True, help_text='The viewer session that created this comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='viewer.viewersession')),
                ('viewer_token', models.ForeignKey(help_text='The viewer token through which this comment was created', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='viewer.viewertoken')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'target_type', '-created_at'], name='viewer_view_documen_228c8d_idx'), models.Index(fields=['content_type', 'object_id'], name='viewer_view_content_38b281_idx'), models.Index(fields=['viewer_token', '-created_at'], name='viewer_view_viewer__ff0a36_idx'), models.Index(fields=['author_email'], name='viewer_view_author__0b7728_idx'), models.Index(fields=['is_resolved'], name='viewer_view_is_reso_0e3067_idx')],
            },
        ),
    ]
