# Generated by Django 6.0 on 2026-02-23 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('viewer', '0002_viewercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewerApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_email', models.EmailField(help_text='Email of the reviewer (from viewer session)', max_length=254)),
                ('reviewer_name', models.CharField(blank=True, default='', help_text='Display name of the reviewer', max_length=255)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], help_text='Approval decision', max_length=20)),
                ('comment', models.TextField(blank=True, default='', help_text='Optional comment with the approval decision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(help_text='The document being approved/rejected', on_delete=django.db.models.deletion.CASCADE, related_name='viewer_approvals', to='documents.document')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='viewer.viewersession')),
                ('viewer_token', models.ForeignKey(blank=True, help_text='The viewer token through which this approval was made', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='viewer.viewertoken')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='viewer_view_documen_d09fb8_idx'), models.Index(fields=['reviewer_email'], name='viewer_view_reviewe_3bd638_idx')],
            },
        ),
    ]
