# Generated by Django 6.0 on 2026-02-23 20:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('viewer', '0003_viewerapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='viewertoken',
            name='allowed_emails',
            field=models.JSONField(blank=True, default=list, help_text='List of emails permitted to access. Empty = anyone can access. E.g. ["alice@law.com", "bob@firm.com"]'),
        ),
        migrations.CreateModel(
            name='ViewerAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('new_comment', 'New Comment'), ('comment_reply', 'Reply to Comment'), ('comment_resolved', 'Comment Resolved'), ('comment_deleted', 'Comment Deleted'), ('approval_submitted', 'Approval Decision Submitted'), ('document_shared', 'Document Shared')], max_length=30)),
                ('message', models.TextField(help_text='Human-readable alert message')),
                ('recipient_email', models.EmailField(help_text='Email of the person who should see this alert', max_length=254)),
                ('triggered_by_email', models.EmailField(blank=True, default='', help_text='Email of the person who triggered this alert', max_length=254)),
                ('triggered_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='viewer.viewerapproval')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='viewer.viewercomment')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_alerts', to='documents.document')),
                ('recipient_user', models.ForeignKey(blank=True, help_text='Auto-linked Django user (if exists)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewer_alerts_received', to=settings.AUTH_USER_MODEL)),
                ('viewer_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='viewer.viewertoken')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_email', 'is_read', '-created_at'], name='viewer_view_recipie_1ff7ef_idx'), models.Index(fields=['recipient_user', 'is_read', '-created_at'], name='viewer_view_recipie_b871ca_idx'), models.Index(fields=['document', '-created_at'], name='viewer_view_documen_d784f0_idx'), models.Index(fields=['alert_type'], name='viewer_view_alert_t_424546_idx')],
            },
        ),
    ]
