# Generated by Django 6.0 on 2026-02-24 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_viewertoken_allowed_emails_vieweralert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewercomment',
            name='viewer_token',
            field=models.ForeignKey(blank=True, help_text='The viewer token through which this comment was created (null for editor-created comments)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='viewer.viewertoken'),
        ),
    ]
