# Generated by Django 6.0 on 2026-02-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_viewer_comment_nullable_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewertoken',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer — read-only PDF'), ('commentator', 'Commentator — can comment and approve')], default='viewer', max_length=20),
        ),
    ]
