# Generated by Django 6.0 on 2026-02-12 17:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0002_document_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('extraction_template', models.JSONField(blank=True, default=dict, help_text='Auto-built from rule nodes: {"field_name": "", ...}')),
                ('canvas_state', models.JSONField(blank=True, default=dict, help_text='{"zoom": 1, "panX": 0, "panY": 0}')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clm_workflows', to='user_management.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='clm/documents/%Y/%m/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('doc', 'Word (legacy)'), ('txt', 'Text')], default='pdf', max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('original_text', models.TextField(blank=True, default='')),
                ('extracted_metadata', models.JSONField(blank=True, default=dict, help_text='Structured JSON from NuExtract, keyed by field names from rule nodes')),
                ('extraction_confidence', models.JSONField(blank=True, default=dict)),
                ('overall_confidence', models.FloatField(blank=True, null=True)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clm_documents', to='user_management.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clm.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('input', 'Input'), ('rule', 'Rule'), ('output', 'Output')], max_length=10)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('position_x', models.FloatField(default=100)),
                ('position_y', models.FloatField(default=200)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='clm.workflow')),
            ],
            options={
                'ordering': ['position_x', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='clm.workflow')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='clm.workflownode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='clm.workflownode')),
            ],
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['organization', 'is_active'], name='clm_workflo_organiz_abd2eb_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdocument',
            index=models.Index(fields=['workflow', 'extraction_status'], name='clm_workflo_workflo_8c1a5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nodeconnection',
            unique_together={('source_node', 'target_node')},
        ),
    ]
