# Generated by Django 6.0 on 2026-02-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdocument',
            name='global_confidence',
            field=models.JSONField(blank=True, default=dict, help_text='Per-field confidence scores for global_metadata'),
        ),
        migrations.AddField(
            model_name='workflowdocument',
            name='global_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Standard CLM fields (party names, dates, values, etc.) from GLOBAL_CLM_TEMPLATE'),
        ),
        migrations.AlterField(
            model_name='workflowdocument',
            name='extracted_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Workflow-specific fields from rule-node conditions, used by filters'),
        ),
    ]
