# Generated by Django 6.0 on 2026-02-13 06:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0002_workflowdocument_global_confidence_and_more'),
        ('user_management', '0002_document_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdocument',
            name='direct_text',
            field=models.TextField(blank=True, default='', help_text='Text extracted directly from file (PyMuPDF, python-docx, etc.)'),
        ),
        migrations.AddField(
            model_name='workflowdocument',
            name='ocr_text',
            field=models.TextField(blank=True, default='', help_text='Text extracted via OCR (tesseract) for scanned/image PDFs'),
        ),
        migrations.AddField(
            model_name='workflowdocument',
            name='text_source',
            field=models.CharField(choices=[('direct', 'Direct'), ('ocr', 'OCR'), ('none', 'None')], default='none', help_text='Which text source was used for extraction', max_length=10),
        ),
        migrations.AlterField(
            model_name='workflowdocument',
            name='original_text',
            field=models.TextField(blank=True, default='', help_text='The text actually used for AI extraction (best of direct/ocr)'),
        ),
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(db_index=True, help_text='Snake_case field name (e.g., party_1_name, contract_value)', max_length=255)),
                ('source', models.CharField(choices=[('global', 'Global (Standard CLM)'), ('workflow', 'Workflow-specific')], default='global', max_length=10)),
                ('raw_value', models.TextField(blank=True, default='', help_text='Original value as returned by NuExtract model')),
                ('standardized_value', models.TextField(blank=True, default='', help_text='Standardized value (dates→YYYY-MM-DD, currency→decimal, etc.)')),
                ('display_value', models.TextField(blank=True, default='', help_text='Human-friendly display value')),
                ('confidence', models.FloatField(default=0.0)),
                ('needs_review', models.BooleanField(default=False)),
                ('is_manually_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='clm.workflowdocument')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clm_extracted_fields', to='user_management.organization')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='clm.workflow')),
            ],
            options={
                'ordering': ['field_name'],
                'indexes': [models.Index(fields=['workflow', 'field_name'], name='clm_extract_workflo_e73ad4_idx'), models.Index(fields=['organization', 'field_name'], name='clm_extract_organiz_1846b6_idx'), models.Index(fields=['field_name', 'standardized_value'], name='clm_extract_field_n_4256fc_idx')],
                'unique_together': {('document', 'field_name', 'source')},
            },
        ),
    ]
