# Generated by Django 6.0 on 2026-02-14 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0003_workflowdocument_direct_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlugin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Machine-readable name: send_email, send_whatsapp, send_sms, etc.', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-friendly label: "Send Email", "Send WhatsApp Message"', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='⚡', help_text='Emoji or short icon identifier for frontend display', max_length=10)),
                ('category', models.CharField(choices=[('communication', 'Communication'), ('notification', 'Notification'), ('integration', 'Integration'), ('export', 'Export'), ('custom', 'Custom')], default='communication', max_length=50)),
                ('required_fields', models.JSONField(blank=True, default=list, help_text='List of metadata field names this plugin needs to run')),
                ('optional_fields', models.JSONField(blank=True, default=list, help_text='Optional metadata fields the plugin can use')),
                ('settings_schema', models.JSONField(blank=True, default=dict, help_text='JSON schema for plugin-specific settings (subject template, message body, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(choices=[('input', 'Input'), ('rule', 'Rule'), ('action', 'Action'), ('output', 'Output')], max_length=10),
        ),
        migrations.CreateModel(
            name='ActionExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial (some failed)'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_documents', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('settings_used', models.JSONField(blank=True, default=dict, help_text='The plugin settings that were used for this execution run')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_executions', to='clm.workflownode')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_executions', to='clm.workflow')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='clm.actionplugin')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionExecutionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('skipped', 'Skipped (missing data)'), ('failed', 'Failed'), ('retried', 'Retried')], default='skipped', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='The data extracted from this document that was sent to the plugin')),
                ('missing_fields', models.JSONField(blank=True, default=list, help_text='List of required field names that were null/empty')),
                ('plugin_response', models.JSONField(blank=True, default=dict, help_text='Response data from the plugin (message ID, delivery status, etc.)')),
                ('error_message', models.TextField(blank=True, default='')),
                ('override_data', models.JSONField(blank=True, default=dict, help_text='User-provided data to override missing/incorrect extracted values')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_results', to='clm.workflowdocument')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='clm.actionexecution')),
            ],
            options={
                'ordering': ['status', 'created_at'],
                'indexes': [models.Index(fields=['execution', 'status'], name='clm_actione_executi_fb9ac0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='actionexecution',
            index=models.Index(fields=['workflow', 'node'], name='clm_actione_workflo_99430b_idx'),
        ),
        migrations.AddIndex(
            model_name='actionexecution',
            index=models.Index(fields=['status'], name='clm_actione_status_bdd349_idx'),
        ),
    ]
