# Generated by Django 6.0 on 2026-02-14 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0004_actionplugin_alter_workflownode_node_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(choices=[('input', 'Input'), ('rule', 'Rule'), ('action', 'Action'), ('listener', 'Listener'), ('output', 'Output')], max_length=10),
        ),
        migrations.CreateModel(
            name='ListenerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('document_uploaded', 'Document Uploaded'), ('approval_required', 'Approval Required'), ('field_changed', 'Field Changed'), ('all_documents_ready', 'All Documents Ready'), ('document_count', 'Document Count Threshold'), ('manual', 'Manual Trigger'), ('schedule', 'Scheduled')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending (awaiting action)'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_fired', 'Auto-Fired (conditions met)'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('document_ids', models.JSONField(blank=True, default=list, help_text='List of document UUIDs involved in this event')),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('event_data', models.JSONField(blank=True, default=dict, help_text='Additional context: {field_name, old_value, new_value, trigger_detail, ...}')),
                ('message', models.TextField(blank=True, default='', help_text='Human-readable description of the event')),
                ('resolution_note', models.TextField(blank=True, default='', help_text='Optional note when approving/rejecting')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('downstream_executed', models.BooleanField(default=False, help_text='Whether downstream nodes were executed as a result')),
                ('execution_result', models.JSONField(blank=True, default=dict, help_text='Result from downstream execution, if any')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listener_events', to='clm.workflownode')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who approved/rejected this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_listener_events', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_listener_events', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listener_events', to='clm.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow', 'status'], name='clm_listene_workflo_175e81_idx'), models.Index(fields=['node', 'status'], name='clm_listene_node_id_51bc66_idx'), models.Index(fields=['trigger_type', 'status'], name='clm_listene_trigger_41c415_idx')],
            },
        ),
    ]
