# Generated by Django 6.0 on 2026-02-14 20:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0005_alter_workflownode_node_type_listenerevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(choices=[('input', 'Input'), ('rule', 'Rule'), ('listener', 'Listener'), ('validator', 'Validator'), ('action', 'Action'), ('output', 'Output')], max_length=10),
        ),
        migrations.CreateModel(
            name='ValidationLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level_number', models.PositiveIntegerField(default=1, help_text='Sequential level (1 = first gate, 2 = second gate, …)')),
                ('name', models.CharField(default='Review', help_text='Human-readable level name: "Legal Review", "Manager Sign-off"', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('require_all', models.BooleanField(default=False, help_text='True = every assigned validator must approve; False = one is enough')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_levels', to='clm.workflownode')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_levels', to='clm.workflow')),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='ValidationDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, default='', help_text='Validator comment / reason')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='The user who needs to make this decision', on_delete=django.db.models.deletion.CASCADE, related_name='clm_pending_validations', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_decisions', to='clm.workflowdocument')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_decisions', to='clm.workflownode')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_decisions', to='clm.workflow')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='clm.validationlevel')),
            ],
            options={
                'ordering': ['level__level_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_label', models.CharField(blank=True, default='', help_text='Display label: "Legal Counsel", "VP Operations"', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clm_validation_assignments', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='clm.validationlevel')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='validationlevel',
            index=models.Index(fields=['node', 'level_number'], name='clm_validat_node_id_223d6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='validationlevel',
            unique_together={('node', 'level_number')},
        ),
        migrations.AddIndex(
            model_name='validationdecision',
            index=models.Index(fields=['assigned_to', 'status'], name='clm_validat_assigne_e89b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='validationdecision',
            index=models.Index(fields=['workflow', 'status'], name='clm_validat_workflo_e7b326_idx'),
        ),
        migrations.AddIndex(
            model_name='validationdecision',
            index=models.Index(fields=['node', 'document', 'status'], name='clm_validat_node_id_f4d362_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='validationdecision',
            unique_together={('level', 'document', 'assigned_to')},
        ),
        migrations.AlterUniqueTogether(
            name='validationassignment',
            unique_together={('level', 'user')},
        ),
    ]
