# Generated by Django 6.0 on 2026-02-14 20:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0006_alter_workflownode_node_type_validationlevel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatorUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_label', models.CharField(blank=True, default='', help_text='Display label: "Legal Counsel", "VP Operations"', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='validationassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='validationassignment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='validationassignment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='validationlevel',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='validationlevel',
            name='clm_validat_node_id_223d6a_idx',
        ),
        migrations.AlterModelOptions(
            name='validationdecision',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='validationdecision',
            unique_together={('node', 'document', 'assigned_to')},
        ),
        migrations.AddField(
            model_name='validatoruser',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validator_users', to='clm.workflownode'),
        ),
        migrations.AddField(
            model_name='validatoruser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clm_validator_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='validatoruser',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validator_users', to='clm.workflow'),
        ),
        migrations.DeleteModel(
            name='ValidationAssignment',
        ),
        migrations.RemoveField(
            model_name='validationdecision',
            name='level',
        ),
        migrations.AlterUniqueTogether(
            name='validatoruser',
            unique_together={('node', 'user')},
        ),
        migrations.DeleteModel(
            name='ValidationLevel',
        ),
    ]
