# Generated by Django 6.0 on 2026-02-14 21:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0007_validatoruser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='auto_execute_on_upload',
            field=models.BooleanField(default=False, help_text='Automatically execute the workflow when new documents are uploaded'),
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('mode', models.CharField(choices=[('full', 'Full (all documents)'), ('batch', 'Batch (selected documents)'), ('single', 'Single document'), ('auto', 'Auto (on upload)')], default='full', max_length=10)),
                ('total_documents', models.PositiveIntegerField(default=0)),
                ('included_document_ids', models.JSONField(blank=True, default=list, help_text='Document UUIDs that were included in this execution')),
                ('excluded_document_ids', models.JSONField(blank=True, default=list, help_text='Document UUIDs that were explicitly excluded')),
                ('output_document_ids', models.JSONField(blank=True, default=list, help_text='Final output document UUIDs after all filtering')),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Full execution result: node_results, action_results, etc.')),
                ('node_summary', models.JSONField(blank=True, default=list, help_text='[{node_id, node_type, label, count, status}, ...]')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='clm.workflow')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['workflow', 'status'], name='clm_workflo_workflo_0c0359_idx'), models.Index(fields=['mode'], name='clm_workflo_mode_5abdd7_idx')],
            },
        ),
    ]
