# Generated by Django 6.0 on 2026-02-15 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0009_alter_workflownode_node_type'),
        ('user_management', '0002_document_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdocument',
            name='email_message_id',
            field=models.CharField(blank=True, default='', help_text='RFC Message-ID header for email dedup (e.g. <abc@mail.gmail.com>)', max_length=500),
        ),
        migrations.AddIndex(
            model_name='workflowdocument',
            index=models.Index(fields=['workflow', 'email_message_id'], name='clm_workflo_workflo_1c21c7_idx'),
        ),
    ]
