# Generated by Django 6.0 on 2026-02-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0010_email_message_id_dedup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(choices=[('input', 'Input'), ('rule', 'Rule'), ('listener', 'Listener'), ('validator', 'Validator'), ('action', 'Action'), ('ai', 'AI'), ('and_gate', 'AND Gate'), ('or_gate', 'OR Gate'), ('output', 'Output')], max_length=10),
        ),
    ]
