# Generated by Django 6.0 on 2026-02-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0012_remove_or_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowdocument',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('doc', 'Word (legacy)'), ('txt', 'Text'), ('csv', 'CSV'), ('json', 'JSON'), ('xml', 'XML'), ('html', 'HTML'), ('md', 'Markdown'), ('xlsx', 'Excel'), ('xls', 'Excel (legacy)'), ('png', 'PNG Image'), ('jpg', 'JPEG Image'), ('jpeg', 'JPEG Image'), ('gif', 'GIF Image'), ('bmp', 'BMP Image'), ('tiff', 'TIFF Image'), ('tif', 'TIFF Image'), ('webp', 'WebP Image'), ('svg', 'SVG Image'), ('rtf', 'Rich Text'), ('odt', 'OpenDocument'), ('other', 'Other')], default='pdf', max_length=20),
        ),
    ]
