# Generated by Django 6.0 on 2026-02-15 18:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0013_alter_workflowdocument_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_hash', models.CharField(db_index=True, help_text='SHA-256 hex digest of model_id + full_system_prompt + document_context', max_length=64, unique=True)),
                ('model_id', models.CharField(max_length=100)),
                ('output_format', models.CharField(default='text', help_text='json_extract | yes_no | text', max_length=20)),
                ('response_text', models.TextField()),
                ('parsed_result', models.JSONField(blank=True, default=dict, help_text='Pre-parsed result: {answer, parsed_fields, response, ...}')),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Prompt Cache',
                'verbose_name_plural': 'AI Prompt Cache Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_id'], name='clm_aipromp_model_i_7b24d0_idx')],
            },
        ),
    ]
