# Generated by Django 6.0 on 2026-02-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0014_aipromptcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdocument',
            name='ocr_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='File-level metadata: page_count, word_count, language, dimensions, ocr_confidence, is_scanned, has_images, has_tables, author, etc.'),
        ),
        migrations.AlterField(
            model_name='workflowdocument',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('archived', 'Archived')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowdocument',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('doc', 'Word (legacy)'), ('txt', 'Text'), ('csv', 'CSV'), ('json', 'JSON'), ('xml', 'XML'), ('html', 'HTML'), ('md', 'Markdown'), ('xlsx', 'Excel'), ('xls', 'Excel (legacy)'), ('pptx', 'PowerPoint'), ('ppt', 'PowerPoint (legacy)'), ('png', 'PNG Image'), ('jpg', 'JPEG Image'), ('jpeg', 'JPEG Image'), ('gif', 'GIF Image'), ('bmp', 'BMP Image'), ('tiff', 'TIFF Image'), ('tif', 'TIFF Image'), ('webp', 'WebP Image'), ('svg', 'SVG Image'), ('rtf', 'Rich Text'), ('odt', 'OpenDocument'), ('other', 'Other')], default='pdf', max_length=20),
        ),
    ]
