# Generated by Django 6.0 on 2026-02-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0015_workflowdocument_ocr_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(choices=[('input', 'Input'), ('rule', 'Rule'), ('listener', 'Listener'), ('validator', 'Validator'), ('action', 'Action'), ('ai', 'AI'), ('and_gate', 'AND Gate'), ('scraper', 'Scraper'), ('output', 'Output')], max_length=10),
        ),
    ]
