# Generated by Django 6.0 on 2026-02-17 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0016_add_scraper_node_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Snake_case field name (e.g., total_experience, risk_score)', max_length=255)),
                ('display_name', models.CharField(blank=True, default='', help_text='Human-friendly label (e.g., "Total Experience (Years)")', max_length=255)),
                ('field_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('list', 'List'), ('category', 'Category')], default='string', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='What this derived field represents')),
                ('computation_hint', models.TextField(help_text='Instructions for the AI on HOW to compute this field. E.g. "Sum all work experience durations to get total years of experience"')),
                ('depends_on', models.JSONField(blank=True, default=list, help_text='List of metadata field names this derived field needs as input. E.g. ["work_experience_1_duration", "work_experience_2_duration"]')),
                ('allowed_values', models.JSONField(blank=True, default=list, help_text='For category type: list of allowed values. E.g. ["junior", "mid", "senior", "lead", "executive"]')),
                ('include_document_text', models.BooleanField(default=False, help_text='If True, includes the full document text in the AI prompt. Useful for fields that need deeper analysis beyond extracted metadata.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Processing order — fields are computed sequentially so later fields can depend on earlier derived fields.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_fields', to='clm.workflow')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['workflow', 'order'], name='clm_derived_workflo_eed569_idx')],
                'unique_together': {('workflow', 'name')},
            },
        ),
    ]
