# Generated by Django 6.0 on 2026-02-17 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0017_derivedfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField(help_text='The user message or the assistant reply text')),
                ('actions', models.JSONField(blank=True, default=list, help_text='List of structured actions: [{action, params, result}, ...]')),
                ('actions_applied', models.BooleanField(default=False, help_text='Whether the proposed actions were actually applied to the workflow')),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='clm.workflow')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['workflow', 'created_at'], name='clm_workflo_workflo_57a6dd_idx')],
            },
        ),
    ]
