# Generated by Django 6.0 on 2026-02-17 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0018_workflowchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdocument',
            name='input_node',
            field=models.ForeignKey(blank=True, help_text='The input node this document was uploaded/ingested through', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_documents', to='clm.workflownode'),
        ),
        migrations.AddField(
            model_name='workflowdocument',
            name='last_extracted_template',
            field=models.JSONField(blank=True, default=dict, help_text='The extraction template used during the last extraction run'),
        ),
    ]
