# Generated by Django 6.0 on 2026-02-18 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0019_workflowdocument_input_node_and_more'),
        ('user_management', '0002_document_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdocument',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 hex digest of the uploaded file content for dedup', max_length=64),
        ),
        migrations.AddIndex(
            model_name='workflowdocument',
            index=models.Index(fields=['workflow', 'file_hash'], name='clm_workflo_workflo_742ac7_idx'),
        ),
    ]
