# Generated by Django 6.0 on 2026-02-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0020_workflowdocument_file_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeconnection',
            name='source_handle',
            field=models.CharField(blank=True, default='', help_text='Handle id on the source node (e.g. "approved", "rejected").', max_length=50),
        ),
    ]
