# Generated by Django 6.0 on 2026-02-19 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0021_nodeconnection_source_handle'),
        ('user_management', '0002_document_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='is_live',
            field=models.BooleanField(default=False, help_text='When True, background poller checks listener nodes automatically.'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, help_text='Last time the background poller checked this workflow.', null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='live_since',
            field=models.DateTimeField(blank=True, help_text='When the workflow was last set to live.', null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='poll_interval_seconds',
            field=models.PositiveIntegerField(default=300, help_text='How often (in seconds) the live poller checks this workflow. Default 5 min.'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['is_live', 'is_active'], name='clm_workflo_is_live_b2f151_idx'),
        ),
    ]
