# Generated by Django 6.0 on 2026-02-19 06:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0022_workflow_is_live_workflow_last_polled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowUploadLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('label', models.CharField(blank=True, default='', help_text='Optional label, e.g. "Vendor portal" or "Client intake"', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, default='', help_text='If set, uploaders must enter this password before uploading.', max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Link expires after this datetime. Null = never expires.', null=True)),
                ('max_uploads', models.PositiveIntegerField(blank=True, help_text='Max number of upload sessions. Null = unlimited.', null=True)),
                ('upload_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('input_node', models.ForeignKey(blank=True, help_text='If set, uploads go to this specific input node.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_links', to='clm.workflownode')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_links', to='clm.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
