# Generated by Django 6.0 on 2026-02-20 06:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0023_add_workflow_upload_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowuploadlink',
            name='require_login',
            field=models.CharField(choices=[('none', 'No login required'), ('email_otp', 'Email OTP verification'), ('phone_otp', 'Phone OTP verification')], default='none', help_text='Whether uploaders must verify identity via OTP before uploading.', max_length=20),
        ),
        migrations.CreateModel(
            name='UploadLinkOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(help_text='Email address or phone number the OTP was sent to.', max_length=255)),
                ('code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('session_token', models.UUIDField(default=uuid.uuid4, help_text='Returned after verification — used as bearer for upload.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('upload_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='clm.workflowuploadlink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
