# Generated by Django 6.0 on 2026-02-20 07:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0024_add_require_login_and_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='nodes_config_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 of all node configs + connections. Changes = re-execute all.', max_length=64),
        ),
        migrations.CreateModel(
            name='DocumentExecutionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_hash', models.CharField(help_text='SHA-256 of the document file content when executed', max_length=64)),
                ('nodes_config_hash', models.CharField(help_text='Workflow nodes_config_hash when this doc was executed', max_length=64)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='completed', max_length=20)),
                ('result_snapshot', models.JSONField(blank=True, default=dict, help_text='Per-node output summary for this document in this execution')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_records', to='clm.workflowdocument')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_records', to='clm.workflowexecution')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_records', to='clm.workflow')),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['workflow', 'file_hash'], name='clm_documen_workflo_f1acde_idx'), models.Index(fields=['workflow', 'nodes_config_hash'], name='clm_documen_workflo_ae4af1_idx'), models.Index(fields=['workflow', 'document'], name='clm_documen_workflo_95b518_idx')],
                'unique_together': {('workflow', 'document', 'nodes_config_hash')},
            },
        ),
    ]
