# Generated by Django 6.0 on 2026-02-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0025_smart_execution'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workflow',
            name='clm_workflo_is_live_b2f151_idx',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='is_live',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='last_polled_at',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='live_since',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='poll_interval_seconds',
        ),
    ]
