# Generated by Django 6.0 on 2026-03-01 18:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0026_remove_live_mode'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(choices=[('input', 'Input'), ('rule', 'Rule'), ('listener', 'Listener'), ('validator', 'Validator'), ('action', 'Action'), ('ai', 'AI'), ('and_gate', 'AND Gate'), ('scraper', 'Scraper'), ('doc_create', 'Document Creator'), ('output', 'Output')], max_length=10),
        ),
        migrations.CreateModel(
            name='DocumentCreationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('skipped', 'Skipped (missing data)'), ('failed', 'Failed')], default='created', max_length=20)),
                ('creation_mode', models.CharField(choices=[('template', 'From Template'), ('duplicate', 'Duplicate Existing'), ('quick_latex', 'Quick LaTeX'), ('structured', 'Structured')], default='template', max_length=20)),
                ('metadata_used', models.JSONField(blank=True, default=dict, help_text='Extracted metadata that was mapped into the editor document')),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clm_creation_records', to='documents.document')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_creation_results', to='clm.workflownode')),
                ('source_clm_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_editor_documents', to='clm.workflowdocument')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_creation_results', to='clm.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow', 'node'], name='clm_documen_workflo_2521ea_idx'), models.Index(fields=['source_clm_document'], name='clm_documen_source__203515_idx'), models.Index(fields=['status'], name='clm_documen_status_768b92_idx')],
            },
        ),
    ]
