# Generated by Django 6.0 on 2026-03-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0027_alter_workflownode_node_type_documentcreationresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(choices=[('input', 'Input'), ('rule', 'Rule'), ('listener', 'Listener'), ('validator', 'Validator'), ('action', 'Action'), ('ai', 'AI'), ('and_gate', 'AND Gate'), ('scraper', 'Scraper'), ('doc_create', 'Document Creator'), ('inference', 'Inference'), ('output', 'Output')], max_length=10),
        ),
    ]
