# Generated by Django 6.0 on 2026-03-11 22:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0028_alter_workflownode_node_type'),
        ('user_management', '0006_rename_general_to_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputNodeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('upload', 'Upload'), ('folder_upload', 'Folder Upload'), ('dms_import', 'DMS Import'), ('bulk_upload', 'Bulk Upload'), ('sheets', 'Sheets Import'), ('email_inbox', 'Email Inbox'), ('google_drive', 'Google Drive'), ('dropbox', 'Dropbox'), ('onedrive', 'OneDrive'), ('s3', 'S3'), ('ftp', 'FTP'), ('url_scrape', 'URL Scrape'), ('table', 'Table/Spreadsheet')], default='upload', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial (some failed)'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('document_ids', models.JSONField(blank=True, default=list, help_text='List of WorkflowDocument UUIDs created in this input operation')),
                ('source_reference', models.JSONField(blank=True, default=dict, help_text='Source details: folder_id, sheet_id, file_names, email_subject, etc.')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Extra details: duplicates_skipped, zip_expanded, errors, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_histories', to='clm.workflownode')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clm_input_histories', to='user_management.organization')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_histories', to='clm.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow', 'node'], name='clm_inputno_workflo_89f756_idx'), models.Index(fields=['node', 'source_type'], name='clm_inputno_node_id_497a96_idx'), models.Index(fields=['organization', '-created_at'], name='clm_inputno_organiz_b773a9_idx')],
            },
        ),
    ]
