# Generated by Django 6.0 on 2026-03-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0029_inputnodehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownode',
            name='document_state',
            field=models.JSONField(blank=True, default=dict, help_text='Per-node document ownership & readiness state'),
        ),
    ]
