# Generated by Django 6.0 on 2026-03-13 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0030_add_document_state_to_workflownode'),
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(choices=[('input', 'Input'), ('rule', 'Rule'), ('listener', 'Listener'), ('validator', 'Validator'), ('action', 'Action'), ('ai', 'AI'), ('and_gate', 'AND Gate'), ('scraper', 'Scraper'), ('doc_create', 'Document Creator'), ('inference', 'Inference'), ('sheet', 'Sheet'), ('output', 'Output')], max_length=10),
        ),
        migrations.CreateModel(
            name='SheetNodeQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('append', 'Append')], default='write', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cached', 'Cached (skipped — duplicate)'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('row_order', models.IntegerField(blank=True, help_text='Row order in the sheet (null for newly appended rows)', null=True)),
                ('row_id', models.UUIDField(blank=True, help_text='SheetRow UUID that was read/written', null=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 of the row payload — used for write dedup cache', max_length=64)),
                ('row_data', models.JSONField(blank=True, default=dict, help_text='Cell values: {"col_key": "value", ...}')),
                ('hit_count', models.PositiveIntegerField(default=0, help_text='Number of times this exact write was deduplicated')),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_queries', to='clm.workflowexecution')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_queries', to='clm.workflownode')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_queries', to='sheets.sheet')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_queries', to='clm.workflowdocument')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_queries', to='clm.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['node', 'sheet', 'content_hash'], name='clm_sheetno_node_id_72a367_idx'), models.Index(fields=['workflow', 'execution'], name='clm_sheetno_workflo_3f9c90_idx'), models.Index(fields=['sheet', 'operation'], name='clm_sheetno_sheet_i_c412bb_idx')],
            },
        ),
    ]
