# Generated by Django 6.0 on 2026-03-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0031_alter_workflownode_node_type_sheetnodequery'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='is_live',
            field=models.BooleanField(default=False, help_text='When True, the workflow auto-executes periodically via Celery Beat'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='live_interval',
            field=models.PositiveIntegerField(default=60, help_text='Live execution interval in seconds (default 60)'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20),
        ),
    ]
