# Generated by Django 6.0 on 2026-03-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0032_async_live_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='current_execution_id',
            field=models.UUIDField(blank=True, help_text='ID of the currently active WorkflowExecution (null when idle).', null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='execution_state',
            field=models.CharField(choices=[('idle', 'Idle'), ('compiling', 'Compiling DAG'), ('executing', 'Executing nodes'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', help_text='Current execution lifecycle state — maintained by executor, read by frontend.', max_length=20),
        ),
    ]
