# Generated by Django 6.0 on 2026-03-20 02:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0033_workflow_current_execution_id_and_more'),
        ('user_management', '0006_rename_general_to_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='compilation_errors',
            field=models.JSONField(blank=True, default=list, help_text='Errors from the last compilation attempt'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='compilation_status',
            field=models.CharField(choices=[('not_compiled', 'Not Compiled'), ('compiled', 'Compiled'), ('stale', 'Stale (nodes changed since last compile)'), ('failed', 'Compilation Failed')], default='not_compiled', help_text='Whether this workflow has been successfully compiled for live execution', max_length=20),
        ),
        migrations.AddField(
            model_name='workflow',
            name='compiled_at',
            field=models.DateTimeField(blank=True, help_text='When the workflow was last successfully compiled', null=True),
        ),
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sheet', 'Sheet Update'), ('email', 'Email Inbox'), ('webhook', 'Webhook'), ('upload', 'File Upload'), ('google_drive', 'Google Drive'), ('dropbox', 'Dropbox'), ('onedrive', 'OneDrive'), ('s3', 'AWS S3'), ('ftp', 'FTP/SFTP'), ('url_scrape', 'URL Scrape'), ('folder', 'Folder Watch'), ('dms', 'DMS Import')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('source_id', models.CharField(blank=True, db_index=True, default='', help_text='UUID or identifier of the source (sheet_id, folder_id, etc.)', max_length=255)),
                ('webhook_token', models.UUIDField(blank=True, help_text='Unique token for webhook URL: /api/clm/webhooks/<token>/', null=True, unique=True)),
                ('webhook_secret', models.CharField(blank=True, default='', help_text='HMAC secret for verifying webhook payloads', max_length=255)),
                ('poll_interval', models.PositiveIntegerField(default=60, help_text='Polling interval in seconds (for email, cloud, etc.)')),
                ('last_polled_at', models.DateTimeField(blank=True, help_text='Last time this subscription was polled/checked', null=True)),
                ('next_poll_at', models.DateTimeField(blank=True, help_text='Scheduled next poll time (for dispatcher efficiency)', null=True)),
                ('consecutive_errors', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('total_events_received', models.PositiveIntegerField(default=0)),
                ('total_executions_triggered', models.PositiveIntegerField(default=0)),
                ('config_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of relevant node.config at compilation time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_subscriptions', to='clm.workflownode')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clm_event_subscriptions', to='user_management.organization')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_subscriptions', to='clm.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('input_document_ids', models.JSONField(blank=True, default=list, help_text='Document IDs that flowed into this node')),
                ('output_document_ids', models.JSONField(blank=True, default=list, help_text='Document IDs that flowed out of this node')),
                ('input_count', models.PositiveIntegerField(default=0)),
                ('output_count', models.PositiveIntegerField(default=0)),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Full node execution result (type-specific: action, AI, etc.)')),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_traceback', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('dag_level', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_logs', to='clm.workflowexecution')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='clm.workflownode')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_execution_logs', to='clm.workflow')),
            ],
            options={
                'ordering': ['dag_level', 'started_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='Event type: sheet_updated, email_received, webhook_call, poll_result, etc.', max_length=50)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored'), ('retrying', 'Retrying')], default='received', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Raw event payload (webhook body, sheet changes, email metadata)')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='HTTP headers (for webhooks)')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict, help_text='Processing result: execution_id, documents_created, etc.')),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', help_text='For dedup — e.g. Message-ID for emails, delivery_id for webhooks', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_events', to='clm.workflowexecution')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clm_webhook_events', to='user_management.organization')),
                ('subscription', models.ForeignKey(blank=True, help_text='The subscription that received this event (null for unmatched webhooks)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clm.eventsubscription')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='clm.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowCompilation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('warning', 'Success with Warnings'), ('failed', 'Failed')], max_length=20)),
                ('node_count', models.PositiveIntegerField(default=0)),
                ('connection_count', models.PositiveIntegerField(default=0)),
                ('has_cycle', models.BooleanField(default=False)),
                ('has_input_node', models.BooleanField(default=True)),
                ('has_output_node', models.BooleanField(default=True)),
                ('subscriptions_created', models.PositiveIntegerField(default=0)),
                ('subscription_details', models.JSONField(blank=True, default=list, help_text='[{node_id, source_type, source_id, poll_interval}, ...]')),
                ('errors', models.JSONField(blank=True, default=list, help_text='[{node_id, message, severity}, ...]')),
                ('warnings', models.JSONField(blank=True, default=list, help_text='[{node_id, message}, ...]')),
                ('config_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compiled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compilations', to='clm.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='eventsubscription',
            index=models.Index(fields=['source_type', 'source_id', 'status'], name='clm_eventsu_source__cdd0b7_idx'),
        ),
        migrations.AddIndex(
            model_name='eventsubscription',
            index=models.Index(fields=['workflow', 'status'], name='clm_eventsu_workflo_0b0919_idx'),
        ),
        migrations.AddIndex(
            model_name='eventsubscription',
            index=models.Index(fields=['webhook_token'], name='clm_eventsu_webhook_d082d7_idx'),
        ),
        migrations.AddIndex(
            model_name='eventsubscription',
            index=models.Index(fields=['status', 'next_poll_at'], name='clm_eventsu_status_93db1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventsubscription',
            unique_together={('workflow', 'node', 'source_type')},
        ),
        migrations.AddIndex(
            model_name='nodeexecutionlog',
            index=models.Index(fields=['execution', 'node'], name='clm_nodeexe_executi_4589aa_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeexecutionlog',
            index=models.Index(fields=['workflow', 'node'], name='clm_nodeexe_workflo_e59ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeexecutionlog',
            index=models.Index(fields=['execution', 'dag_level'], name='clm_nodeexe_executi_2cbfda_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeexecutionlog',
            index=models.Index(fields=['status'], name='clm_nodeexe_status_d5b018_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nodeexecutionlog',
            unique_together={('execution', 'node')},
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_type', 'status'], name='clm_webhook_event_t_98e4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['workflow', 'status'], name='clm_webhook_workflo_6e1633_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['subscription', '-created_at'], name='clm_webhook_subscri_567e79_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['idempotency_key'], name='clm_webhook_idempot_9bd97d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowcompilation',
            index=models.Index(fields=['workflow', '-created_at'], name='clm_workflo_workflo_668fb7_idx'),
        ),
    ]
