# Generated by Django 6.0 on 2026-03-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0034_workflow_compilation_errors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowexecution',
            name='trigger_context',
            field=models.JSONField(blank=True, default=dict, help_text='Event payload that triggered this execution (changed rows, source info, etc.)'),
        ),
    ]
