# Generated by Django 6.0 on 2026-03-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0035_workflowexecution_trigger_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetnodequery',
            name='operation',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('append', 'Append'), ('upsert', 'Upsert (unique-key match)')], default='write', max_length=10),
        ),
    ]
