# Generated by Django 6.0 on 2026-03-21 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0036_alter_sheetnodequery_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowLiveEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('execution_started', 'Execution Started'), ('execution_completed', 'Execution Completed'), ('node_started', 'Node Started'), ('node_completed', 'Node Completed'), ('node_failed', 'Node Failed'), ('node_progress', 'Node Progress'), ('document_processed', 'Document Processed'), ('compilation_started', 'Compilation Started'), ('compilation_done', 'Compilation Done'), ('live_tick', 'Live Tick'), ('metric_update', 'Metric Update')], max_length=30)),
                ('node_type', models.CharField(blank=True, default='', max_length=20)),
                ('node_label', models.CharField(blank=True, default='', max_length=255)),
                ('input_count', models.PositiveIntegerField(default=0)),
                ('output_count', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('progress_pct', models.FloatField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Event-specific data: errors, document_ids, metrics, etc.')),
                ('status', models.CharField(blank=True, default='', help_text='Node/execution status at time of event: running, completed, failed', max_length=20)),
                ('dag_level', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_events', to='clm.workflowexecution')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_events', to='clm.workflownode')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_events', to='clm.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow', '-created_at'], name='clm_workflo_workflo_8debd0_idx'), models.Index(fields=['workflow', 'execution', 'event_type'], name='clm_workflo_workflo_6f1a93_idx'), models.Index(fields=['workflow', 'event_type', '-created_at'], name='clm_workflo_workflo_bb5e2b_idx'), models.Index(fields=['execution', 'dag_level', 'created_at'], name='clm_workflo_executi_5b3cd5_idx'), models.Index(fields=['node', '-created_at'], name='clm_workflo_node_id_89751d_idx')],
            },
        ),
    ]
