# Generated by Django 6.0 on 2026-03-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0037_workflowliveevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsubscription',
            name='source_type',
            field=models.CharField(choices=[('sheet', 'Sheet Update'), ('document', 'Document Update'), ('email', 'Email Inbox'), ('webhook', 'Webhook'), ('upload', 'File Upload'), ('google_drive', 'Google Drive'), ('dropbox', 'Dropbox'), ('onedrive', 'OneDrive'), ('s3', 'AWS S3'), ('ftp', 'FTP/SFTP'), ('url_scrape', 'URL Scrape'), ('folder', 'Folder Watch'), ('dms', 'DMS Import')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inputnodehistory',
            name='source_type',
            field=models.CharField(choices=[('upload', 'Upload'), ('folder_upload', 'Folder Upload'), ('dms_import', 'DMS Import'), ('bulk_upload', 'Bulk Upload'), ('sheets', 'Sheets Import'), ('document', 'Document Update'), ('email_inbox', 'Email Inbox'), ('google_drive', 'Google Drive'), ('dropbox', 'Dropbox'), ('onedrive', 'OneDrive'), ('s3', 'S3'), ('ftp', 'FTP'), ('url_scrape', 'URL Scrape'), ('table', 'Table/Spreadsheet')], default='upload', max_length=20),
        ),
    ]
