# Generated by Django 6.0 on 2026-03-22 13:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0038_alter_eventsubscription_source_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_id', models.CharField(db_index=True, help_text='Stable row identity (SheetRow UUID or WorkflowDocument UUID)', max_length=255)),
                ('content_hash', models.CharField(help_text='SHA-256 of row data when action was executed', max_length=64)),
                ('action_type', models.CharField(blank=True, default='', help_text='Plugin name or action type (e.g. send_email, create_document)', max_length=50)),
                ('status', models.CharField(default='executed', help_text='executed | skipped | failed', max_length=20)),
                ('result_summary', models.JSONField(blank=True, default=dict, help_text='Brief result data (plugin response, created doc id, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(blank=True, help_text='The execution that created this log entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='row_action_logs', to='clm.workflowexecution')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_action_logs', to='clm.workflownode')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_action_logs', to='clm.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['node', 'row_id', 'content_hash'], name='rowactionlog_node_row_hash_idx'), models.Index(fields=['workflow', 'node', '-created_at'], name='clm_rowacti_workflo_3df17d_idx'), models.Index(fields=['created_at'], name='clm_rowacti_created_0ec509_idx')],
                'unique_together': {('node', 'row_id', 'content_hash')},
            },
        ),
    ]
