# Generated by Django 6.0 on 2026-03-22 20:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0039_row_action_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputNodeRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_id', models.CharField(help_text='Stable row identity (SheetRow UUID)', max_length=255)),
                ('content_hash', models.CharField(help_text='SHA-256 of row data when last ingested', max_length=64)),
                ('source_type', models.CharField(default='sheets', help_text='sheets | sheet_node | table', max_length=30)),
                ('sheet_id', models.CharField(blank=True, default='', help_text='Sheet UUID (for sheet sources)', max_length=255)),
                ('row_order', models.IntegerField(blank=True, help_text='Row order at time of ingestion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(help_text='The WorkflowDocument created for this row', on_delete=django.db.models.deletion.CASCADE, related_name='input_node_rows', to='clm.workflowdocument')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_node_rows', to='clm.workflownode')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_node_rows', to='clm.workflow')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['node', 'row_id'], name='inputnoderow_node_rowid_idx'), models.Index(fields=['node', 'content_hash'], name='inputnoderow_node_hash_idx'), models.Index(fields=['workflow', 'node'], name='inputnoderow_wf_node_idx')],
                'unique_together': {('node', 'row_id')},
            },
        ),
    ]
