# Generated by Django 6.0 on 2026-03-28 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0040_input_node_row'),
        ('user_management', '0008_input_node_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Optional team that manages this workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clm_workflows', to='user_management.team'),
        ),
    ]
