# Generated by Django 6.0 on 2026-03-28 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0041_add_team_to_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='trigger_mode',
            field=models.CharField(choices=[('manual', 'Manual Only'), ('event', 'Event-Driven'), ('scheduled', 'Scheduled'), ('hybrid', 'Hybrid (Manual + Events)')], default='manual', help_text='How this workflow is triggered: manual, event-driven, scheduled, or hybrid', max_length=20),
        ),
        migrations.AddField(
            model_name='workflow',
            name='workflow_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Workflow-level configuration. Schema:\n        {\n          "validation": {\n            "approval_rule": "any"|"all"|"majority",   // any=first approve wins, all=unanimous, majority=50%+1\n            "require_note": false,                      // force validators to add a note\n            "auto_approve_timeout_hours": null,          // auto-approve after N hours (null=disabled)\n            "notification_channels": ["in_app", "email"] // where to notify validators\n          },\n          "execution": {\n            "retry_on_failure": false,\n            "max_retries": 3,\n            "retry_delay_seconds": 60,\n            "notify_on_complete": true,\n            "notify_on_failure": true,\n            "timeout_minutes": null,                     // max execution time (null=unlimited)\n            "parallel_nodes": true                       // execute independent nodes in parallel\n          },\n          "general": {\n            "description_long": "",\n            "tags": [],\n            "color": "",                                 // workflow accent color\n            "icon": ""                                   // workflow icon\n          }\n        }'),
        ),
        migrations.CreateModel(
            name='WorkflowEventTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text='Human-readable trigger name', max_length=255)),
                ('trigger_type', models.CharField(choices=[('webhook', 'Webhook'), ('schedule', 'Scheduled'), ('file_upload', 'File Upload'), ('email', 'Email Arrival'), ('sheet_update', 'Sheet Update'), ('field_change', 'Field Value Change'), ('document_status', 'Document Status Change'), ('manual', 'Manual Only'), ('api_call', 'API Call')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Trigger-specific configuration (varies by type)')),
                ('webhook_token', models.UUIDField(blank=True, help_text='Unique token for webhook triggers: /api/clm/triggers/<token>/', null=True, unique=True)),
                ('webhook_secret', models.CharField(blank=True, default='', help_text='HMAC secret for webhook payload verification', max_length=255)),
                ('next_run_at', models.DateTimeField(blank=True, help_text='Next scheduled trigger time (for schedule type)', null=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('total_triggers', models.PositiveIntegerField(default=0)),
                ('total_executions', models.PositiveIntegerField(default=0)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_triggers', to='clm.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow', 'is_active'], name='clm_workflo_workflo_153a8f_idx'), models.Index(fields=['trigger_type', 'is_active'], name='clm_workflo_trigger_d1aa78_idx'), models.Index(fields=['webhook_token'], name='clm_workflo_webhook_5b1ef6_idx'), models.Index(fields=['next_run_at'], name='clm_workflo_next_ru_8ad85b_idx')],
            },
        ),
    ]
