# Generated by Django 6.0 on 2026-03-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0042_workflow_trigger_mode_workflow_workflow_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowexecution',
            name='config_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Frozen copy of workflow config at execution time: nodes, connections, extraction_template, nodes_config_hash'),
        ),
    ]
