# Generated by Django 6.0 on 2026-03-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0043_workflowexecution_config_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedfield',
            name='raw_value',
            field=models.TextField(blank=True, default='', help_text='Original value as returned by AI extraction'),
        ),
    ]
