# Generated by Django 6.0 on 2026-02-28 02:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiservices', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAIConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('services_config', models.JSONField(blank=True, default=dict, help_text='\n\t\tPer-document AI service overrides.  Same schema as\n\t\tDocumentTypeAIPreset.services_config.  Values here take\n\t\tprecedence over the document-type preset.\n\t')),
                ('system_prompt', models.TextField(blank=True, default='', help_text='Per-document custom system prompt override')),
                ('ai_focus', models.TextField(blank=True, default='', help_text='Per-document AI focus instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(help_text='The document this AI config belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document AI Config',
                'verbose_name_plural': 'Document AI Configs',
            },
        ),
        migrations.CreateModel(
            name='DocumentTypeAIPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(db_index=True, help_text="Maps to Document.document_type, e.g. 'contract', 'billing', 'nda'", max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, default='', help_text="Human-friendly label for the UI, e.g. 'Billing Documents'", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Explanation of how AI services are tuned for this type')),
                ('services_config', models.JSONField(blank=True, default=dict, help_text='\n\t\tMaster config dict keyed by service name.  Each value is a dict:\n\t\t{\n\t\t\t"document_scoring": {\n\t\t\t\t"enabled": true,\n\t\t\t\t"mode": "legal",        // "legal" | "financial" | "data" | "custom"\n\t\t\t\t"model": "gemini-3-flash-preview",\n\t\t\t\t"temperature": 0.0,\n\t\t\t\t"max_tokens": 4000,\n\t\t\t\t"system_prompt_override": null,\n\t\t\t\t"options": {}\n\t\t\t},\n\t\t\t"paragraph_review": {\n\t\t\t\t"enabled": true,\n\t\t\t\t"mode": "legal",\n\t\t\t\t"model": null,\n\t\t\t\t"system_prompt_override": null,\n\t\t\t\t"options": {}\n\t\t\t},\n\t\t\t"paragraph_scoring": {\n\t\t\t\t"enabled": false,        // e.g. turned off for billing docs\n\t\t\t\t"mode": "data",\n\t\t\t\t"model": null,\n\t\t\t\t"options": {}\n\t\t\t},\n\t\t\t"data_validation": {\n\t\t\t\t"enabled": true,\n\t\t\t\t"mode": "financial",\n\t\t\t\t"system_prompt_override": "You are a financial data validator...",\n\t\t\t\t"options": {\n\t\t\t\t\t"validate_calculations": true,\n\t\t\t\t\t"check_totals": true,\n\t\t\t\t\t"currency_format": "USD"\n\t\t\t\t}\n\t\t\t},\n\t\t\t"chat": { "enabled": true, "mode": "legal" },\n\t\t\t"analysis": { "enabled": true },\n\t\t\t"generation": { "enabled": true },\n\t\t\t"paragraph_rewrite": { "enabled": true }\n\t\t}\n\t')),
                ('system_prompt', models.TextField(blank=True, default='', help_text='Custom system prompt prepended to every AI call for this document type')),
                ('ai_focus', models.TextField(blank=True, default='', help_text="Free-form instruction describing what the AI should focus on for this document type.  E.g. 'Focus on numerical accuracy, totals, tax calculations, and line-item correctness.'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document-Type AI Preset',
                'verbose_name_plural': 'Document-Type AI Presets',
                'ordering': ['document_type'],
            },
        ),
    ]
