# Generated by Django 6.0 on 2026-02-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiservices', '0002_documentaiconfig_documenttypeaipreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaiconfig',
            name='service_prompts',
            field=models.JSONField(blank=True, default=dict, help_text="\n\t\tPer-document per-service system prompt overrides.\n\t\tSame schema as DocumentTypeAIPreset.service_prompts.\n\t\tKeys here override the preset's service_prompts for this document.\n\t"),
        ),
        migrations.AddField(
            model_name='documenttypeaipreset',
            name='service_prompts',
            field=models.JSONField(blank=True, default=dict, help_text='\n\t\tPer-service system prompts keyed by service name.  When a service\n\t\tmakes an AI call, the prompt for that service is used *instead* of\n\t\tthe global system_prompt.  If a service has no entry here, the\n\t\tglobal system_prompt is used as fallback.\n\t\t{\n\t\t\t"document_scoring": "You are a legal quality assessor...",\n\t\t\t"paragraph_review": "You are a paragraph-level legal reviewer...",\n\t\t\t"paragraph_scoring": "You are a paragraph scoring specialist...",\n\t\t\t"paragraph_rewrite": "You are a legal document editor...",\n\t\t\t"data_validation": "You are a financial data validator...",\n\t\t\t"chat": "You are a helpful legal document assistant...",\n\t\t\t"analysis": "You are a legal document analyst...",\n\t\t\t"generation": "You are a legal content generator..."\n\t\t}\n\t'),
        ),
    ]
