# Generated by Django 6.0 on 2026-03-05 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiservices', '0003_add_service_prompts'),
        ('contenttypes', '__first__'),
        ('documents', '0002_add_viewer_token_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentInference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('component_type', models.CharField(choices=[('section', 'Section'), ('paragraph', 'Paragraph'), ('sentence', 'Sentence'), ('latex_code', 'LaTeX Code'), ('table', 'Table')], db_index=True, max_length=20)),
                ('summary', models.TextField(blank=True, default='', help_text='1-3 sentence natural-language summary')),
                ('key_entities', models.JSONField(blank=True, default=list, help_text='Extracted named entities, legal terms, monetary values')),
                ('context_tags', models.JSONField(blank=True, default=list, help_text='Classification tags: obligation, definition, condition, etc.')),
                ('relationships', models.JSONField(blank=True, default=list, help_text='Cross-references to other components [{target_id, relation_type, description}]')),
                ('sentiment', models.FloatField(blank=True, help_text='Sentiment polarity -1.0 (negative) to 1.0 (positive)', null=True)),
                ('complexity', models.FloatField(blank=True, help_text='Readability/complexity score 0.0 (simple) to 1.0 (complex)', null=True)),
                ('importance', models.FloatField(default=0.5, help_text='Relevance weight 0.0-1.0 for parent aggregation')),
                ('embedding_json', models.JSONField(blank=True, help_text='Float vector for semantic similarity (optional)', null=True)),
                ('raw_llm_output', models.JSONField(blank=True, help_text='Full LLM response for audit', null=True)),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 of source text at inference time', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=200)),
                ('document_version_number', models.IntegerField(db_index=True, default=1)),
                ('is_latest', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inference_duration_ms', models.IntegerField(blank=True, help_text='Inference wall-time in milliseconds', null=True)),
                ('custom_metadata', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_inferences', to='documents.document')),
                ('section', models.ForeignKey(blank=True, help_text='Parent section (for all component types)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_inferences', to='documents.section')),
            ],
            options={
                'verbose_name': 'Component Inference',
                'verbose_name_plural': 'Component Inferences',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'is_latest'], name='aiservices__content_0131ed_idx'), models.Index(fields=['document', 'component_type', 'is_latest'], name='aiservices__documen_6b5609_idx'), models.Index(fields=['section', 'is_latest'], name='aiservices__section_18aecb_idx'), models.Index(fields=['content_hash'], name='aiservices__content_88e9f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentInferenceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, default='')),
                ('section_summaries', models.JSONField(blank=True, default=list, help_text='[{section_id, title, summary, importance, tags}]')),
                ('all_entities', models.JSONField(blank=True, default=list)),
                ('all_tags', models.JSONField(blank=True, default=list)),
                ('all_relationships', models.JSONField(blank=True, default=list)),
                ('avg_sentiment', models.FloatField(blank=True, null=True)),
                ('avg_complexity', models.FloatField(blank=True, null=True)),
                ('total_sections', models.IntegerField(default=0)),
                ('total_components', models.IntegerField(default=0)),
                ('sections_hash', models.CharField(db_index=True, max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=200)),
                ('document_version_number', models.IntegerField(db_index=True, default=1)),
                ('is_latest', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inference_duration_ms', models.IntegerField(blank=True, null=True)),
                ('custom_metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_summaries', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'is_latest'], name='aiservices__documen_89eca1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SectionAggregateInference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, default='', help_text='Merged summary of all children — 3-5 sentences')),
                ('child_summaries', models.JSONField(blank=True, default=list, help_text='Ordered list of {component_id, component_type, summary, importance}')),
                ('aggregated_entities', models.JSONField(blank=True, default=list, help_text='Union of all child key_entities, deduplicated')),
                ('aggregated_tags', models.JSONField(blank=True, default=list, help_text='Union of all child context_tags, deduplicated')),
                ('aggregated_relationships', models.JSONField(blank=True, default=list, help_text='All cross-references from children')),
                ('avg_sentiment', models.FloatField(blank=True, null=True)),
                ('avg_complexity', models.FloatField(blank=True, null=True)),
                ('max_importance', models.FloatField(blank=True, null=True)),
                ('total_components', models.IntegerField(default=0)),
                ('total_paragraphs', models.IntegerField(default=0)),
                ('total_sentences', models.IntegerField(default=0)),
                ('total_tables', models.IntegerField(default=0)),
                ('total_latex_codes', models.IntegerField(default=0)),
                ('total_subsections', models.IntegerField(default=0)),
                ('children_hash', models.CharField(db_index=True, help_text='SHA-256 of sorted child content hashes — detects any subtree change', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=200)),
                ('document_version_number', models.IntegerField(db_index=True, default=1)),
                ('is_latest', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inference_duration_ms', models.IntegerField(blank=True, null=True)),
                ('custom_metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_aggregate_inferences', to='documents.document')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_inferences', to='documents.section')),
            ],
            options={
                'verbose_name': 'Section Aggregate Inference',
                'verbose_name_plural': 'Section Aggregate Inferences',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['section', 'is_latest'], name='aiservices__section_14e7b7_idx'), models.Index(fields=['document', 'is_latest'], name='aiservices__documen_13ac07_idx'), models.Index(fields=['children_hash'], name='aiservices__childre_b1e6fe_idx')],
            },
        ),
    ]
