# Generated by Django 6.0 on 2026-03-07 01:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiservices', '0004_componentinference_documentinferencesummary_and_more'),
        ('contenttypes', '__first__'),
        ('documents', '0002_add_viewer_token_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateralEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_object_id', models.UUIDField()),
                ('target_object_id', models.UUIDField()),
                ('edge_type', models.CharField(choices=[('critical', 'Critical'), ('contextual', 'Contextual')], db_index=True, help_text='CRITICAL (≥0.85) or CONTEXTUAL (0.65–0.84)', max_length=20)),
                ('score', models.FloatField(help_text='Cross-encoder relevance score (0.0–1.0)')),
                ('target_summary', models.TextField(blank=True, default='', help_text='Snapshot of target ComponentInference.summary at edge creation time')),
                ('target_label', models.CharField(blank=True, default='', help_text='Human-readable label: section title + component type', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(help_text='Owning document (for fast bulk queries / cleanup)', on_delete=django.db.models.deletion.CASCADE, related_name='lateral_edges', to='documents.document')),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lateral_edge_sources', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lateral_edge_targets', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Lateral Edge',
                'verbose_name_plural': 'Lateral Edges',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['source_content_type', 'source_object_id'], name='idx_lateral_source'), models.Index(fields=['target_content_type', 'target_object_id'], name='idx_lateral_target'), models.Index(fields=['document'], name='idx_lateral_document'), models.Index(fields=['document', 'edge_type'], name='idx_lateral_doc_type')],
            },
        ),
    ]
