# Generated by Django 6.0 on 2025-12-30 15:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Organization name', max_length=255, unique=True)),
                ('legal_name', models.CharField(blank=True, help_text='Legal business name', max_length=255, null=True)),
                ('organization_type', models.CharField(choices=[('law_firm', 'Law Firm'), ('corporation', 'Corporation'), ('government', 'Government Agency'), ('nonprofit', 'Non-Profit'), ('individual', 'Individual/Sole Practitioner'), ('other', 'Other')], default='corporation', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID/EIN', max_length=50, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/%Y/%m/')),
                ('primary_color', models.CharField(default='#1E40AF', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(default='#6B7280', help_text='Hex color code', max_length=7)),
                ('subscription_plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=50)),
                ('max_users', models.IntegerField(default=5, help_text='Maximum number of users allowed')),
                ('max_documents', models.IntegerField(default=100, help_text='Maximum number of documents')),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Organization-specific settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='user_manage_name_86ae46_idx'), models.Index(fields=['is_active'], name='user_manage_is_acti_0fa37c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Role name (e.g., 'Admin', 'Editor')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable role name', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('role_type', models.CharField(choices=[('system_admin', 'System Administrator'), ('org_admin', 'Organization Administrator'), ('legal_reviewer', 'Legal Reviewer'), ('editor', 'Editor'), ('viewer', 'Viewer'), ('guest', 'Guest'), ('custom', 'Custom Role')], default='viewer', max_length=50)),
                ('permissions', models.JSONField(default=dict, help_text='Permission settings')),
                ('is_system_role', models.BooleanField(default=False, help_text='System-defined role (cannot be deleted)')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['name'], name='user_manage_name_d5bb2c_idx'), models.Index(fields=['role_type'], name='user_manage_role_ty_861e9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/%Y/%m/')),
                ('bar_number', models.CharField(blank=True, help_text='Bar association number', max_length=50, null=True)),
                ('license_state', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='User-specific preferences')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Email verified')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_location', models.CharField(blank=True, max_length=255, null=True)),
                ('login_count', models.IntegerField(default=0)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('account_locked_until', models.DateTimeField(blank=True, null=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('force_password_change', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='user_management.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='user_management.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='Visible to all org members')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='user_management.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to='user_management.userprofile')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to='user_management.userprofile')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='user_management.userprofile')),
            ],
            options={
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('token', models.CharField(max_length=100, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, help_text='Optional message to invitee', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Invitation expiry date')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='user_management.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.role')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['organization', 'is_active'], name='user_manage_organiz_ae116c_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='user_manage_role_id_371a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['organization', 'is_active'], name='user_manage_organiz_7a5434_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='invitationtoken',
            index=models.Index(fields=['token'], name='user_manage_token_cc25e4_idx'),
        ),
        migrations.AddIndex(
            model_name='invitationtoken',
            index=models.Index(fields=['email', 'is_used'], name='user_manage_email_52267e_idx'),
        ),
    ]
