# Generated by ChatGPT on 2026-01-20

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDocumentSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_document_type', models.CharField(default='contract', max_length=100)),
                ('default_status', models.CharField(default='draft', max_length=50)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('require_etag', models.BooleanField(default=True)),
                ('enable_versioning', models.BooleanField(default=True)),
                ('allow_external_sharing', models.BooleanField(default=False)),
                ('retention_days', models.IntegerField(default=365, help_text='Retention policy in days')),
                ('auto_save_interval_seconds', models.IntegerField(default=30)),
                ('max_file_size_mb', models.IntegerField(default=25)),
                ('allowed_file_types', models.JSONField(blank=True, default=list)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_settings', to='user_management.organization')),
            ],
            options={
                'ordering': ['organization'],
            },
        ),
        migrations.CreateModel(
            name='UserDocumentSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_save_enabled', models.BooleanField(default=True)),
                ('auto_save_interval_seconds', models.IntegerField(default=30)),
                ('change_tracking_enabled', models.BooleanField(default=True)),
                ('show_change_markers', models.BooleanField(default=True)),
                ('default_view', models.CharField(choices=[('edit', 'Edit'), ('preview', 'Preview'), ('diff', 'Diff')], default='edit', max_length=20)),
                ('ai_assist_enabled', models.BooleanField(default=True)),
                ('notification_on_mentions', models.BooleanField(default=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_settings', to='user_management.userprofile')),
            ],
            options={
                'ordering': ['profile'],
            },
        ),
    ]
