# Generated by Django 6.0 on 2026-03-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_login_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='domain',
            field=models.CharField(choices=[('legal', 'Legal'), ('finance', 'Finance & Banking'), ('healthcare', 'Healthcare'), ('real_estate', 'Real Estate'), ('insurance', 'Insurance'), ('technology', 'Technology'), ('education', 'Education'), ('government', 'Government'), ('consulting', 'Consulting'), ('general', 'General / Other')], default='general', help_text='Industry domain — determines default feature flags', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Per-org overrides on top of domain defaults. Use __removed__ to revert a flag.'),
        ),
    ]
