# Generated by Django 6.0 on 2026-03-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_organization_domain_organization_feature_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='domain',
            field=models.CharField(choices=[('procurement', 'Procurement'), ('legal', 'Legal'), ('finance', 'Finance & Banking'), ('healthcare', 'Healthcare'), ('real_estate', 'Real Estate'), ('insurance', 'Insurance'), ('technology', 'Technology'), ('education', 'Education'), ('government', 'Government'), ('consulting', 'Consulting'), ('general', 'General / Other')], default='general', help_text='Industry domain — determines default feature flags', max_length=50),
        ),
    ]
