# Generated by Django 6.0 on 2026-03-11 10:15

from django.db import migrations, models


def rename_general_to_default(apps, schema_editor):
    """Update all existing organizations from 'general' to 'default'."""
    Organization = apps.get_model('user_management', 'Organization')
    Organization.objects.filter(domain='general').update(domain='default')


def rename_default_to_general(apps, schema_editor):
    """Reverse: revert 'default' back to 'general'."""
    Organization = apps.get_model('user_management', 'Organization')
    Organization.objects.filter(domain='default').update(domain='general')


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_organization_domain'),
    ]

    operations = [
        # First, update existing data while the old choices are still valid
        migrations.RunPython(rename_general_to_default, rename_default_to_general),
        # Then alter the field to the new choices
        migrations.AlterField(
            model_name='organization',
            name='domain',
            field=models.CharField(choices=[('default', 'Default (All Features)'), ('procurement', 'Procurement'), ('legal', 'Legal'), ('finance', 'Finance & Banking'), ('healthcare', 'Healthcare'), ('real_estate', 'Real Estate'), ('insurance', 'Insurance'), ('technology', 'Technology'), ('education', 'Education'), ('government', 'Government'), ('consulting', 'Consulting')], default='default', help_text='Industry domain — determines default feature flags', max_length=50),
        ),
    ]
