# Generated by Django 6.0 on 2026-03-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_rename_general_to_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdocumentsettings',
            name='default_ai_model',
            field=models.CharField(default='gemini-2.5-flash', help_text='Default AI model for CLM nodes, document analysis, etc.', max_length=100),
        ),
    ]
