# Generated by Django 6.0 on 2026-03-27 21:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_default_ai_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputNodeCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='User-facing name, e.g. "Work Gmail" or "Contracts S3"', max_length=120)),
                ('credential_type', models.CharField(choices=[('email_inbox', 'Email / IMAP'), ('google_drive', 'Google Drive'), ('dropbox', 'Dropbox'), ('onedrive', 'OneDrive / SharePoint'), ('s3', 'AWS S3'), ('ftp', 'FTP / SFTP')], max_length=30)),
                ('credentials', models.JSONField(default=dict, help_text='Source-specific secrets. Schema depends on credential_type:\n  email_inbox:  {email_host, email_user, email_password}\n  google_drive: {google_access, google_api_key, google_credentials_json}\n  dropbox:      {dropbox_access_token}\n  onedrive:     {onedrive_access_token}\n  s3:           {s3_access_key, s3_secret_key, s3_region}\n  ftp:          {ftp_host, ftp_port, ftp_user, ftp_password, ftp_protocol}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_credentials', to='user_management.userprofile')),
            ],
            options={
                'ordering': ['credential_type', 'label'],
                'indexes': [models.Index(fields=['profile', 'credential_type'], name='user_manage_profile_55e945_idx')],
            },
        ),
    ]
