/**
 * SheetEditorModal — lightweight modal wrapper around the Sheets editor UI.
 *
 * Reuses the existing sheets Zustand store + grid/toolbar/formula bar.
 * This lets other parts of the app (like CLM WorkflowCanvas) edit a sheet
 * without navigating away to /sheets/:id.
 */

import { useEffect, useState, useCallback } from 'react';
import { X, Save, Loader2, ExternalLink, Share2, Link, Copy, ClipboardCheck, Trash2 } from 'lucide-react';

import useSheetsStore from '../../store/sheetsStore';

import SheetToolbar from './SheetToolbar';
import FormulaBar from './FormulaBar';
import SheetGrid from './SheetGrid';

/**
 * Returns true if a column label is a default Excel-style placeholder
 * (A, B, C … Z, AA, AB … etc.) auto-generated by ensure_columns.
 */
const isDefaultColumnLabel = (label) => /^[A-Z]{1,3}$/.test(label || '');

/** Column types that are computed / should never appear in a share form. */
const isNonInputColumn = (col) =>
  isDefaultColumnLabel(col.label) || col.type === 'formula';

export default function SheetEditorModal({
  open,
  sheetId,
  title,
  onClose,
  onSaved,
  showCloseIcon = true,
  navigateToFull,
  /** Optional: workflow + node IDs for linking share links to CLM */
  workflowId,
  workflowNodeId,
}) {
  const fetchSheetPaginated = useSheetsStore((s) => s.fetchSheetPaginated);
  const loadMoreRows = useSheetsStore((s) => s.loadMoreRows);
  const currentSheet = useSheetsStore((s) => s.currentSheet);
  const saveAllCells = useSheetsStore((s) => s.saveAllCells);
  const loading = useSheetsStore((s) => s.loading);
  const saving = useSheetsStore((s) => s.saving);
  const loadingMore = useSheetsStore((s) => s.loadingMore);
  const pagination = useSheetsStore((s) => s.pagination);
  const reset = useSheetsStore((s) => s.reset);

  const [localError, setLocalError] = useState(null);

  // ── Share state ──
  const [showShare, setShowShare] = useState(false);
  const [shareLinks, setShareLinks] = useState([]);
  const [shareLoading, setShareLoading] = useState(false);
  const [creatingLink, setCreatingLink] = useState(false);
  const [copiedToken, setCopiedToken] = useState(null);
  const [selectedColumns, setSelectedColumns] = useState([]);

  useEffect(() => {
    if (!open) return;
    if (!sheetId) return;

    setLocalError(null);
    fetchSheetPaginated(sheetId, 100).catch((e) => {
      setLocalError(e?.message || 'Failed to load sheet');
    });

    return () => reset();
  }, [open, sheetId, fetchSheetPaginated, reset]);

  const handleSave = useCallback(async () => {
    setLocalError(null);
    try {
      await saveAllCells();
      onSaved?.();
    } catch (e) {
      // store swallows errors; keep this as a modal-level guard
      setLocalError(e?.message || 'Failed to save');
    }
  }, [saveAllCells, onSaved]);

  // ── Share handlers ──
  const fetchShareLinks = useCallback(async () => {
    if (!sheetId) return;
    setShareLoading(true);
    try {
      const { sheetsService } = await import('@services/sheetsService');
      const { data } = await sheetsService.listShareLinks(sheetId);
      setShareLinks(data);
    } catch {
      /* swallow */
    } finally {
      setShareLoading(false);
    }
  }, [sheetId]);

  const handleOpenShare = useCallback(() => {
    setShowShare(true);
    fetchShareLinks();
  }, [fetchShareLinks]);

  const handleCreateLink = useCallback(async () => {
    if (!sheetId) return;
    setCreatingLink(true);
    try {
      const { sheetsService } = await import('@services/sheetsService');
      const payload = {
        label: (currentSheet?.title || 'Sheet') + ' Form',
        form_columns: selectedColumns,
      };
      if (workflowId) payload.workflow = workflowId;
      if (workflowNodeId) payload.workflow_node = workflowNodeId;
      await sheetsService.createShareLink(sheetId, payload);
      await fetchShareLinks();
      setSelectedColumns([]);
    } catch {
      /* swallow */
    } finally {
      setCreatingLink(false);
    }
  }, [sheetId, currentSheet, selectedColumns, workflowId, workflowNodeId, fetchShareLinks]);

  const handleCopyLink = useCallback((token) => {
    const url = `${window.location.origin}/sheets/form/${token}`;
    navigator.clipboard.writeText(url);
    setCopiedToken(token);
    setTimeout(() => setCopiedToken(null), 2000);
  }, []);

  const handleToggleLink = useCallback(async (linkId, isActive) => {
    if (!sheetId) return;
    try {
      const { sheetsService } = await import('@services/sheetsService');
      await sheetsService.updateShareLink(sheetId, linkId, { is_active: !isActive });
      await fetchShareLinks();
    } catch {
      /* swallow */
    }
  }, [sheetId, fetchShareLinks]);

  const handleDeleteLink = useCallback(async (linkId) => {
    if (!sheetId) return;
    try {
      const { sheetsService } = await import('@services/sheetsService');
      await sheetsService.deleteShareLink(sheetId, linkId);
      await fetchShareLinks();
    } catch {
      /* swallow */
    }
  }, [sheetId, fetchShareLinks]);

  const toggleColumn = useCallback((key) => {
    setSelectedColumns((prev) =>
      prev.includes(key) ? prev.filter((k) => k !== key) : [...prev, key]
    );
  }, []);

  if (!open) return null;

  return (
    <>
      <div
        className="fixed inset-0 z-[90] bg-black/40 backdrop-blur-sm"
        onClick={() => onClose?.()}
      />
      <div className="fixed inset-0 z-[91] flex items-center justify-center p-4">
        <div className="bg-white w-full max-w-6xl h-[85vh] rounded-2xl shadow-2xl border border-gray-100 overflow-hidden flex flex-col">
          {/* Header */}
          <div className="flex items-center justify-between px-4 py-3 border-b border-gray-100 shrink-0">
            <div className="min-w-0">
              <div className="text-sm font-semibold text-gray-900 truncate">
                {title || currentSheet?.title || 'Sheet'}
              </div>
              {sheetId && (
                <div className="text-[11px] text-gray-400 truncate">
                  {sheetId}
                </div>
              )}
            </div>

            <div className="flex items-center gap-2">
              {navigateToFull && (
                <button
                  onClick={navigateToFull}
                  className="flex items-center gap-1 px-2.5 py-1.5 text-xs font-medium text-gray-600 hover:text-cyan-700 hover:bg-cyan-50 rounded-md transition-colors"
                  title="Open full sheet editor"
                >
                  <ExternalLink className="h-3.5 w-3.5" />
                  More
                </button>
              )}

              {/* Share button */}
              <button
                onClick={handleOpenShare}
                className={`flex items-center gap-1 px-2.5 py-1.5 text-xs font-medium rounded-md transition-colors ${
                  showShare
                    ? 'bg-cyan-100 text-cyan-700'
                    : 'text-gray-600 hover:text-cyan-700 hover:bg-cyan-50'
                }`}
                title="Share sheet as form"
              >
                <Share2 className="h-3.5 w-3.5" />
                Share
              </button>

              {(loading && !currentSheet) ? (
                <span className="text-xs text-gray-500 flex items-center gap-1">
                  <Loader2 className="h-3.5 w-3.5 animate-spin" /> Loading…
                </span>
              ) : (
                <button
                  onClick={handleSave}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium bg-cyan-600 text-white rounded-md hover:bg-cyan-700 transition-colors"
                  disabled={saving || !currentSheet}
                >
                  {saving ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Save className="h-3.5 w-3.5" />}
                  Save
                </button>
              )}

              {showCloseIcon && (
                <button
                  onClick={() => onClose?.()}
                  className="p-1.5 hover:bg-gray-100 rounded transition-colors text-gray-500"
                  title="Close"
                >
                  <X className="h-4 w-4" />
                </button>
              )}
            </div>
          </div>

          {/* ── Share panel (slides down when open) ── */}
          {showShare && (
            <div className="border-b border-gray-100 bg-gray-50/70 px-4 py-3 space-y-3 shrink-0 max-h-[40vh] overflow-y-auto">
              <div className="flex items-center justify-between">
                <h4 className="text-xs font-semibold text-gray-700 flex items-center gap-1.5">
                  <Share2 className="h-3.5 w-3.5 text-cyan-600" />
                  Share as Form
                </h4>
                <button onClick={() => setShowShare(false)} className="text-gray-400 hover:text-gray-600 text-xs">✕</button>
              </div>

              <p className="text-[11px] text-gray-500">
                Create a public link. Anyone with it can submit responses as new rows.
              </p>

              {/* Column picker — only show user-renamed, non-formula columns */}
              {currentSheet?.columns?.filter((c) => !isNonInputColumn(c)).length > 0 && (
                <div>
                  <label className="block text-[10px] text-gray-400 font-semibold uppercase tracking-wider mb-1">
                    Form columns <span className="font-normal">(empty = all)</span>
                  </label>
                  <div className="flex flex-wrap gap-1">
                    {currentSheet.columns
                      .filter((col) => !isNonInputColumn(col))
                      .map((col) => (
                      <button
                        key={col.key}
                        onClick={() => toggleColumn(col.key)}
                        className={`px-2 py-0.5 rounded-full text-[10px] font-medium transition-colors ${
                          selectedColumns.includes(col.key)
                            ? 'bg-cyan-600 text-white'
                            : 'bg-gray-200 text-gray-600 hover:bg-gray-300'
                        }`}
                      >
                        {col.label || col.key}
                      </button>
                    ))}
                  </div>
                </div>
              )}

              {/* Create link */}
              <button
                onClick={handleCreateLink}
                disabled={creatingLink}
                className="flex items-center justify-center gap-1.5 px-3 py-2 w-full text-xs font-medium text-white bg-cyan-600 hover:bg-cyan-700 rounded-lg transition-colors disabled:opacity-50"
              >
                {creatingLink ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Link className="h-3.5 w-3.5" />}
                {creatingLink ? 'Creating…' : 'Create Share Link'}
              </button>

              {/* Existing links */}
              {shareLoading ? (
                <div className="flex items-center justify-center py-3">
                  <Loader2 className="h-4 w-4 animate-spin text-gray-400" />
                </div>
              ) : shareLinks.length > 0 && (
                <div className="space-y-2">
                  {shareLinks.map((lnk) => (
                    <div
                      key={lnk.id}
                      className={`border rounded-lg p-2.5 transition-colors ${
                        lnk.is_active ? 'border-cyan-200 bg-white' : 'border-gray-200 bg-gray-100 opacity-60'
                      }`}
                    >
                      <div className="flex items-center justify-between gap-2">
                        <div className="min-w-0 flex-1">
                          <p className="text-[11px] font-medium text-gray-800 truncate">{lnk.label || 'Share Link'}</p>
                          <p className="text-[10px] text-gray-400 font-mono truncate">
                            {window.location.origin}/sheets/form/{lnk.token}
                          </p>
                          <p className="text-[10px] text-gray-400">
                            {lnk.submission_count} submission{lnk.submission_count !== 1 ? 's' : ''}
                          </p>
                        </div>
                        <div className="flex items-center gap-1 shrink-0">
                          <button
                            onClick={() => handleCopyLink(lnk.token)}
                            className="p-1 hover:bg-cyan-50 rounded text-gray-400 hover:text-cyan-600 transition-colors"
                            title="Copy link"
                          >
                            {copiedToken === lnk.token ? (
                              <ClipboardCheck className="h-3.5 w-3.5 text-emerald-500" />
                            ) : (
                              <Copy className="h-3.5 w-3.5" />
                            )}
                          </button>
                          <button
                            onClick={() => handleToggleLink(lnk.id, lnk.is_active)}
                            className={`text-[9px] px-1.5 py-0.5 rounded-full font-medium transition-colors ${
                              lnk.is_active
                                ? 'bg-emerald-100 text-emerald-700 hover:bg-emerald-200'
                                : 'bg-gray-200 text-gray-600 hover:bg-gray-300'
                            }`}
                          >
                            {lnk.is_active ? 'Active' : 'Off'}
                          </button>
                          <button
                            onClick={() => handleDeleteLink(lnk.id)}
                            className="p-1 hover:bg-red-50 rounded text-gray-400 hover:text-red-500 transition-colors"
                            title="Delete"
                          >
                            <Trash2 className="h-3 w-3" />
                          </button>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {localError && (
            <div className="px-4 py-2 text-xs text-red-600 bg-red-50 border-b border-red-100">
              {localError}
            </div>
          )}

          {/* Editor body */}
          <div className="flex-1 flex flex-col min-h-0">
            <SheetToolbar
              onAIGenerate={null}
              onImportWorkflow={null}
              onImportTable={null}
              onExport={null}
            />
            <FormulaBar />
            <div className="flex-1 min-h-0">
              <SheetGrid onScrollEnd={pagination?.hasNext ? loadMoreRows : undefined} />
            </div>
          </div>

          {/* Footer */}
          <div className="shrink-0 h-9 flex items-center justify-between px-4 border-t border-gray-200 bg-gray-50 text-[11px] text-gray-500">
            <div className="flex items-center gap-3">
              <span>
                {currentSheet?.rows?.length || 0}{pagination ? ` / ${pagination.totalRows}` : ''} rows × {currentSheet?.columns?.filter((c) => !isNonInputColumn(c)).length || currentSheet?.col_count || 0} columns
              </span>
              {pagination?.hasNext && (
                <button
                  onClick={loadMoreRows}
                  disabled={loadingMore}
                  className="flex items-center gap-1 px-2 py-0.5 text-[10px] font-medium text-cyan-700 bg-cyan-50 hover:bg-cyan-100 rounded transition-colors disabled:opacity-50"
                >
                  {loadingMore ? (
                    <><Loader2 className="h-3 w-3 animate-spin" /> Loading…</>
                  ) : (
                    <>Load more (page {pagination.page + 1}/{pagination.totalPages})</>
                  )}
                </button>
              )}
              {pagination && !pagination.hasNext && pagination.totalPages > 1 && (
                <span className="text-[10px] text-emerald-600 font-medium">✓ All rows loaded</span>
              )}
            </div>
            <button
              onClick={async () => {
                await handleSave();
                onClose?.();
              }}
              className="text-[11px] font-medium text-cyan-700 hover:underline disabled:text-gray-400"
              disabled={saving || !currentSheet}
            >
              Save & close
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
