# Generated by Django 6.0 on 2026-03-11 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clm', '0028_alter_workflownode_node_type'),
        ('user_management', '0006_rename_general_to_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Sheet', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('columns', models.JSONField(blank=True, default=list)),
                ('custom_metadata', models.JSONField(blank=True, default=dict)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('col_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='user_management.organization')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheets', to='clm.workflow')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SheetRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_run_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='sheets.sheet')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('sheet', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SheetCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('column_key', models.CharField(max_length=50)),
                ('raw_value', models.TextField(blank=True, default='')),
                ('computed_value', models.TextField(blank=True, default='')),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('formula', 'Formula'), ('error', 'Error')], default='text', max_length=10)),
                ('formula', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='sheets.sheetrow')),
            ],
            options={
                'unique_together': {('row', 'column_key')},
            },
        ),
    ]
