# Generated by Django 6.0 on 2026-03-17 07:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0033_workflow_current_execution_id_and_more'),
        ('sheets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('label', models.CharField(blank=True, default='', help_text='Optional label, e.g. "Vendor intake form"', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Instructions shown at the top of the form.')),
                ('is_active', models.BooleanField(default=True)),
                ('access_type', models.CharField(choices=[('public', 'Public (anyone with link)'), ('email_otp', 'Email OTP verification')], default='public', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_submissions', models.PositiveIntegerField(blank=True, null=True)),
                ('submission_count', models.PositiveIntegerField(default=0)),
                ('form_columns', models.JSONField(blank=True, default=list, help_text='Column keys to include in the form. Empty = all columns.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='sheets.sheet')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_form_links', to='clm.workflow')),
                ('workflow_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_form_links', to='clm.workflownode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SheetFormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('submitter_identifier', models.CharField(blank=True, default='', help_text='Email or identifier of the submitter.', max_length=255)),
                ('submitter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('row', models.ForeignKey(blank=True, help_text='The SheetRow created from this submission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submission', to='sheets.sheetrow')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='sheets.sheet')),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='sheets.sheetsharelink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
