# Generated by Django 6.0 on 2026-03-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_sheetsharelink_sheetformsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetcell',
            name='value_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('currency', 'Currency'), ('boolean', 'Boolean'), ('date', 'Date'), ('json', 'JSON'), ('formula', 'Formula'), ('error', 'Error')], default='text', max_length=10),
        ),
    ]
