# Generated by Django 6.0 on 2026-03-18 07:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_alter_sheetcell_value_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Intelligent Dashboard', max_length=255)),
                ('chart_config', models.JSONField(blank=True, default=dict)),
                ('prompt_used', models.TextField(blank=True, default='')),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('fallback', 'Fallback')], default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='sheets.sheet')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
