# Generated by Django 6.0 on 2026-03-18 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_sheet_dashboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('formula_eval', 'Formula Evaluation'), ('search', 'Search'), ('analytics', 'Analytics'), ('chart_gen', 'Chart Generation'), ('bulk_update', 'Bulk Update'), ('export', 'Export')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('completed_items', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sheetcell',
            index=models.Index(fields=['row', 'column_key'], name='sheetcell_row_colkey_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetcell',
            index=models.Index(fields=['column_key', 'raw_value'], name='sheetcell_col_rawval_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetcell',
            index=models.Index(fields=['value_type'], name='sheetcell_valtype_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetrow',
            index=models.Index(fields=['sheet', 'order'], name='sheetrow_sheet_order_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetrow',
            index=models.Index(fields=['sheet', '-order'], name='sheetrow_sheet_order_desc'),
        ),
        migrations.AddIndex(
            model_name='sheetrow',
            index=models.Index(condition=models.Q(('workflow_run_id__isnull', False)), fields=['workflow_run_id'], name='sheetrow_workflow_run_idx'),
        ),
        migrations.AddField(
            model_name='sheettask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sheettask',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sheets.sheet'),
        ),
        migrations.AddIndex(
            model_name='sheettask',
            index=models.Index(fields=['sheet', 'task_type', '-created_at'], name='sheettask_sheet_type_idx'),
        ),
        migrations.AddIndex(
            model_name='sheettask',
            index=models.Index(fields=['status'], name='sheettask_status_idx'),
        ),
    ]
