# Generated by Django 6.0 on 2026-03-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_enterprise_indexes_and_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetrow',
            name='row_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='sheetrow',
            index=models.Index(fields=['sheet', 'row_hash'], name='sheetrow_sheet_rowhash_idx'),
        ),
    ]
