# Generated by Django 6.0 on 2026-03-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_sheetrow_row_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='unique_columns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
