# Generated by Django 6.0 on 2026-03-21 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0037_workflowliveevent'),
        ('sheets', '0007_sheet_unique_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowExecutionTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_executed_hash', models.CharField(blank=True, default='', help_text='SHA-256 row hash when the workflow was last triggered for this row.', max_length=64)),
                ('last_execution_id', models.UUIDField(blank=True, help_text='UUID of the WorkflowExecution that last processed this row.', null=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='When the workflow was last triggered for this row.', null=True)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0, help_text='How many times triggering failed in a row.')),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_trackers', to='sheets.sheetrow')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_trackers', to='sheets.sheet')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_execution_trackers', to='clm.workflow')),
            ],
            options={
                'indexes': [models.Index(fields=['sheet', 'workflow'], name='rowexectracker_sheet_wf_idx'), models.Index(fields=['last_executed_hash'], name='rowexectracker_hash_idx')],
                'unique_together': {('sheet', 'row', 'workflow')},
            },
        ),
    ]
