# Generated by Django 6.0 on 2026-02-08

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fileshare.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0002_document_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_root', models.BooleanField(default=False)),
                ('root_type', models.CharField(choices=[('personal', 'Personal'), ('shared', 'Shared with me'), ('team', 'Team'), ('organization', 'Organization')], default='personal', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_folders', to='user_management.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_folders', to='auth.user')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fileshare.drivefolder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to=fileshare.models.drive_upload_path)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=150)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='upload', max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='fileshare.drivefolder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_files', to='user_management.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_files', to='auth.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='drivefolder',
            index=models.Index(fields=['organization', 'is_deleted'], name='fileshare_d_organi_248b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='drivefolder',
            index=models.Index(fields=['owner', 'is_deleted'], name='fileshare_d_owner_0d98c6_idx'),
        ),
        migrations.AddIndex(
            model_name='drivefolder',
            index=models.Index(fields=['parent'], name='fileshare_d_parent_0622b3_idx'),
        ),
        migrations.AddIndex(
            model_name='drivefolder',
            index=models.Index(fields=['is_root', 'root_type'], name='fileshare_d_is_root_d51f7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='drivefolder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'parent', 'name'), name='unique_folder_name_in_parent'),
        ),
        migrations.AddIndex(
            model_name='drivefile',
            index=models.Index(fields=['organization', 'is_deleted'], name='fileshare_d_organi_0611de_idx'),
        ),
        migrations.AddIndex(
            model_name='drivefile',
            index=models.Index(fields=['owner', 'is_deleted'], name='fileshare_d_owner_8b8a48_idx'),
        ),
        migrations.AddIndex(
            model_name='drivefile',
            index=models.Index(fields=['folder', 'is_deleted'], name='fileshare_d_folder_4f2b91_idx'),
        ),
        migrations.AddConstraint(
            model_name='drivefile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'folder', 'name'), name='unique_file_name_in_folder'),
        ),
    ]
