# Generated by ChatGPT on 2026-02-09

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_root_drive_scopes(apps, schema_editor):
    DriveFolder = apps.get_model('fileshare', 'DriveFolder')
    DriveFolder.objects.filter(is_root=True).update(drive_scope=models.F('root_type'))


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0001_initial'),
        ('user_management', '0002_document_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefolder',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_folders', to='user_management.team'),
        ),
        migrations.AddField(
            model_name='drivefolder',
            name='drive_scope',
            field=models.CharField(choices=[('personal', 'Personal'), ('shared', 'Shared with me'), ('team', 'Team'), ('organization', 'Organization')], default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='drivefile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_files', to='user_management.team'),
        ),
        migrations.AddField(
            model_name='drivefile',
            name='drive_scope',
            field=models.CharField(choices=[('personal', 'Personal'), ('shared', 'Shared with me'), ('team', 'Team'), ('organization', 'Organization')], default='personal', max_length=20),
        ),
        migrations.CreateModel(
            name='DriveFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='drivefavorite',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_drive_favorite'),
        ),
        migrations.RunPython(set_root_drive_scopes, migrations.RunPython.noop),
    ]
