# Generated by Django 6.0 on 2026-02-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0002_drive_scopes_and_favorites'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='drivefile',
            new_name='fileshare_d_organiz_118303_idx',
            old_name='fileshare_d_organi_0611de_idx',
        ),
        migrations.RenameIndex(
            model_name='drivefile',
            new_name='fileshare_d_owner_i_6c02be_idx',
            old_name='fileshare_d_owner_8b8a48_idx',
        ),
        migrations.RenameIndex(
            model_name='drivefile',
            new_name='fileshare_d_folder__956b01_idx',
            old_name='fileshare_d_folder_4f2b91_idx',
        ),
        migrations.RenameIndex(
            model_name='drivefolder',
            new_name='fileshare_d_organiz_c3ea07_idx',
            old_name='fileshare_d_organi_248b5e_idx',
        ),
        migrations.RenameIndex(
            model_name='drivefolder',
            new_name='fileshare_d_owner_i_1d80d4_idx',
            old_name='fileshare_d_owner_0d98c6_idx',
        ),
        migrations.RenameIndex(
            model_name='drivefolder',
            new_name='fileshare_d_parent__f1219f_idx',
            old_name='fileshare_d_parent_0622b3_idx',
        ),
        migrations.RenameIndex(
            model_name='drivefolder',
            new_name='fileshare_d_is_root_f75049_idx',
            old_name='fileshare_d_is_root_d51f7b_idx',
        ),
    ]
