"""
Django settings for drafter project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

from corsheaders.defaults import default_headers, default_methods

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from env.env in the project root.
load_dotenv(BASE_DIR / 'env.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x3y%5_2ks=qgcp-t)@0)46bbczq7maz$e7gmq#p&w=0x7xjle$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'testserver',
]
# Allow framing from same origin for embedded PDFs / file previews in print pages.
# Default Django value is 'DENY' which prevents embedding; set to 'SAMEORIGIN'
# so files served from this site can be embedded in iframes/embed tags.
X_FRAME_OPTIONS = 'SAMEORIGIN'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'corsheaders',
    # Local apps
    'documents',
    'exporter',
    'aiservices',
    'user_management',
    'sharing',  # Generic sharing system
    'fileshare',
    'dms',
    'clm',  # Contract Lifecycle Management
    'viewer',  # Document viewer & commentator for external users
    'communications',  # Centralized communications, alerts & email system
    'sheets',  # Spreadsheet / data tables app
    'attachments',  # Centralized image & document attachment library
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Add CORS middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'drafter.middleware.DisableCSRFMiddleware',  # Add custom CSRF exemption middleware
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
     "http://localhost:5173",
     "http://127.0.0.1:5173"
]

CORS_ALLOW_CREDENTIALS = True

# Expose ETag header to frontend for concurrency control
CORS_EXPOSE_HEADERS = ['ETag']

# Allow common headers used by frontend (ETag preconditions, JSON)
CORS_ALLOW_HEADERS = list(default_headers) + [
    'If-Match',
    'If-None-Match',
]

# Ensure all write methods are allowed in preflight
CORS_ALLOW_METHODS = list(default_methods) + [
    'PATCH',
    'PUT',
    'DELETE',
]

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
}

ROOT_URLCONF = 'drafter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drafter.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# Allowed upload file types
ALLOWED_DOCUMENT_TYPES = [
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',  # .docx
    'application/msword',  # .doc
    'text/plain',
    'application/rtf',
]

ALLOWED_IMAGE_TYPES = [
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/webp',
]

# Session settings
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS

# CSRF settings
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
]

# Exempt API endpoints from CSRF protection
CSRF_EXEMPT_URLS = [
    r'^api/',
]

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email configuration — SMTP via Gmail with certifi SSL
# NOTE: Google Workspace requires an App Password (not regular password).
# Generate one at: https://myaccount.google.com → Security → App Passwords
# Configure these in env.env (loaded via python-dotenv). Defaults are for local dev only.
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'clm.email_backend.CertifiSMTPBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'mayaramallesh12@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)


X_FRAME_OPTIONS = "SAMEORIGIN"  # allow iframes from same origin
# or
X_FRAME_OPTIONS = "ALLOWALL"    # allow from any origin (not recommended)


# ---------------------------------------------------------------------------
# Celery — Async task queue + periodic beat scheduler
# ---------------------------------------------------------------------------
# Redis as message broker.  Install: brew install redis && redis-server
# Or use SQLite-backed broker for dev (no Redis needed):
#   pip install sqlalchemy  →  CELERY_BROKER_URL = 'sqla+sqlite:///celerydb.sqlite3'
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Beat schedule — master tick every 30s checks which email nodes need polling
CELERY_BEAT_SCHEDULE = {
    'email-inbox-dispatcher': {
        'task': 'clm.tasks.dispatch_email_checks',
        'schedule': 30.0,  # every 30 seconds, lightweight dispatcher
    },
    'live-workflow-dispatcher': {
        'task': 'clm.tasks.dispatch_live_workflows',
        'schedule': 60.0,  # every 60 seconds, dispatches async exec for live workflows
    },
    'event-subscription-dispatcher': {
        'task': 'clm.tasks.dispatch_event_subscriptions',
        'schedule': 30.0,  # every 30 seconds, polls time-based subscriptions (email, cloud, etc.)
    },
    'clm-table-cleanup': {
        'task': 'clm.tasks.cleanup_clm_tables',
        'schedule': 6 * 60 * 60,  # every 6 hours — prunes SheetNodeQuery, NodeExecutionLog, etc.
    },
    # ── Notification system tasks ────────────────────────────────────
    'notification-retry-failed': {
        'task': 'communications.tasks.retry_failed_deliveries',
        'schedule': 60.0,  # every 60 seconds — retry pending failed deliveries
    },
    'notification-digest-hourly': {
        'task': 'communications.tasks.send_digest_emails',
        'schedule': 3600.0,  # every hour
        'args': ('hourly',),
    },
    'notification-digest-daily': {
        'task': 'communications.tasks.send_digest_emails',
        'schedule': 86400.0,  # every 24 hours
        'args': ('daily',),
    },
    'notification-digest-weekly': {
        'task': 'communications.tasks.send_digest_emails',
        'schedule': 604800.0,  # every 7 days
        'args': ('weekly',),
    },
    'notification-cleanup-expired': {
        'task': 'communications.tasks.cleanup_expired_alerts',
        'schedule': 6 * 60 * 60,  # every 6 hours — prune expired & old alerts
    },
}

# django-celery-beat (optional, for dynamic schedules via admin)
# Uncomment and add 'django_celery_beat' to INSTALLED_APPS if desired.
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


# ---------------------------------------------------------------------------
# Django Channels — WebSocket support for real-time notifications
# ---------------------------------------------------------------------------
# Install: pip install channels channels-redis
# The notification WebSocket consumer is at /ws/notifications/
# If channels is not installed, the system gracefully falls back to HTTP-only.

# ASGI application (also set in drafter/asgi.py)
ASGI_APPLICATION = 'drafter.asgi.application'

# Channel layer — uses Redis for cross-process communication
# In production, use the same Redis instance as Celery or a dedicated one.
# For development without Redis, use InMemoryChannelLayer (single-process only).
CHANNEL_LAYERS = {
    'default': {
        # Production: Redis-backed channel layer
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],
            'capacity': 1000,          # max messages per channel
            'expiry': 60,              # message TTL in seconds
        },
    },
    # Uncomment for development without Redis:
    # 'default': {
    #     'BACKEND': 'channels.layers.InMemoryChannelLayer',
    # },
}


# ---------------------------------------------------------------------------
# Notification system settings
# ---------------------------------------------------------------------------
NOTIFICATION_SETTINGS = {
    # Deduplication window (seconds) — alerts with same dedup_key suppressed
    'DEDUP_WINDOW_SECONDS': 300,  # 5 minutes

    # Rate limit: max alerts per user per category within window
    'RATE_LIMIT_WINDOW_SECONDS': 60,
    'RATE_LIMIT_MAX_PER_WINDOW': 20,

    # Alert TTL — auto-expire low-priority alerts after this many days
    'DEFAULT_EXPIRY_DAYS': None,  # None = never expire

    # Cleanup — delete old read+archived alerts after this many days
    'CLEANUP_READ_ARCHIVED_DAYS': 90,
    'CLEANUP_WEBHOOK_LOGS_DAYS': 30,

    # Webhook settings
    'WEBHOOK_TIMEOUT_SECONDS': 10,
    'WEBHOOK_MAX_RETRIES': 3,
    'WEBHOOK_AUTO_DISABLE_THRESHOLD': 10,
}