"""
Django settings for drafter project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from dotenv import load_dotenv

from corsheaders.defaults import default_headers, default_methods

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from env.env in the project root.
load_dotenv(BASE_DIR / 'env.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x3y%5_2ks=qgcp-t)@0)46bbczq7maz$e7gmq#p&w=0x7xjle$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'testserver',
]
# Allow framing from same origin for embedded PDFs / file previews in print pages.
# Default Django value is 'DENY' which prevents embedding; set to 'SAMEORIGIN'
# so files served from this site can be embedded in iframes/embed tags.
X_FRAME_OPTIONS = 'SAMEORIGIN'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'corsheaders',
    # Local apps
    'documents',
    'exporter',
    'aiservices',
    'user_management',
    'sharing',  # Generic sharing system
    'fileshare',
    'dms',
    'clm',  # Contract Lifecycle Management
    'viewer',  # Document viewer & commentator for external users
    'communications',  # Centralized communications, alerts & email system
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Add CORS middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'drafter.middleware.DisableCSRFMiddleware',  # Add custom CSRF exemption middleware
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
     "http://localhost:5173",
     "http://127.0.0.1:5173"
]

CORS_ALLOW_CREDENTIALS = True

# Expose ETag header to frontend for concurrency control
CORS_EXPOSE_HEADERS = ['ETag']

# Allow common headers used by frontend (ETag preconditions, JSON)
CORS_ALLOW_HEADERS = list(default_headers) + [
    'If-Match',
    'If-None-Match',
]

# Ensure all write methods are allowed in preflight
CORS_ALLOW_METHODS = list(default_methods) + [
    'PATCH',
    'PUT',
    'DELETE',
]

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
}

ROOT_URLCONF = 'drafter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drafter.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# Allowed upload file types
ALLOWED_DOCUMENT_TYPES = [
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',  # .docx
    'application/msword',  # .doc
    'text/plain',
    'application/rtf',
]

ALLOWED_IMAGE_TYPES = [
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/webp',
]

# Session settings
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS

# CSRF settings
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
]

# Exempt API endpoints from CSRF protection
CSRF_EXEMPT_URLS = [
    r'^api/',
]

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email configuration — SMTP via Gmail with certifi SSL
# NOTE: Google Workspace requires an App Password (not regular password).
# Generate one at: https://myaccount.google.com → Security → App Passwords
# Replace EMAIL_HOST_PASSWORD with the 16-char app password.
EMAIL_BACKEND = 'clm.email_backend.CertifiSMTPBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'mayaramallesh12@gmail.com'
EMAIL_HOST_PASSWORD = 'cvmwcnjvnppictjg'
DEFAULT_FROM_EMAIL = 'mayaramallesh12@gmail.com'


X_FRAME_OPTIONS = "SAMEORIGIN"  # allow iframes from same origin
# or
X_FRAME_OPTIONS = "ALLOWALL"    # allow from any origin (not recommended)


# ---------------------------------------------------------------------------
# Celery — Async task queue + periodic beat scheduler
# ---------------------------------------------------------------------------
# Redis as message broker.  Install: brew install redis && redis-server
# Or use SQLite-backed broker for dev (no Redis needed):
#   pip install sqlalchemy  →  CELERY_BROKER_URL = 'sqla+sqlite:///celerydb.sqlite3'
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Beat schedule — master tick every 30s checks which email nodes need polling
CELERY_BEAT_SCHEDULE = {
    'email-inbox-dispatcher': {
        'task': 'clm.tasks.dispatch_email_checks',
        'schedule': 30.0,  # every 30 seconds, lightweight dispatcher
    },
}

# django-celery-beat (optional, for dynamic schedules via admin)
# Uncomment and add 'django_celery_beat' to INSTALLED_APPS if desired.
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'