# Generated by Django 6.0 on 2026-03-24 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_viewer_token_fk'),
        ('user_management', '0007_default_ai_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentimage',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization that owns this image (auto-set from uploader)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_images', to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='documentimage',
            name='scope',
            field=models.CharField(choices=[('user', 'User (private)'), ('team', 'Team'), ('organization', 'Organization'), ('document', 'Document-specific')], db_index=True, default='user', help_text='Visibility scope for this image', max_length=20),
        ),
        migrations.AddField(
            model_name='documentimage',
            name='team',
            field=models.ForeignKey(blank=True, help_text="Team scope — required when scope='team'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_images', to='user_management.team'),
        ),
        migrations.AddIndex(
            model_name='documentimage',
            index=models.Index(fields=['scope', '-uploaded_at'], name='documents_d_scope_e6088f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentimage',
            index=models.Index(fields=['organization', '-uploaded_at'], name='documents_d_organiz_a3eda1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentimage',
            index=models.Index(fields=['team', '-uploaded_at'], name='documents_d_team_id_74b1e5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentimage',
            index=models.Index(fields=['organization', 'scope'], name='documents_d_organiz_95fb6b_idx'),
        ),
    ]
