# Generated by Django 6.0 on 2026-03-24 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentimage_organization_documentimage_scope_and_more'),
        ('user_management', '0007_default_ai_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization that owns this file (auto-set from uploader)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_files', to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='team',
            field=models.ForeignKey(blank=True, help_text="Team scope — required when access_level='team'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_files', to='user_management.team'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['organization', '-uploaded_at'], name='documents_d_organiz_f204a6_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['team', '-uploaded_at'], name='documents_d_team_id_f98fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['organization', 'access_level'], name='documents_d_organiz_d5a4f5_idx'),
        ),
    ]
