# Generated by Django 6.0 on 2026-03-24 04:26

import attachments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_add_viewer_token_fk'),
        ('user_management', '0007_default_ai_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='User-friendly display name', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_kind', models.CharField(choices=[('image', 'Image'), ('document', 'Document / PDF'), ('other', 'Other')], db_index=True, default='image', help_text='Broad category: image or document', max_length=20)),
                ('image_type', models.CharField(blank=True, choices=[('logo', 'Company/Organization Logo'), ('watermark', 'Watermark Image'), ('background', 'Background Image'), ('header_icon', 'Header Icon'), ('footer_icon', 'Footer Icon'), ('signature', 'Signature Image'), ('stamp', 'Stamp/Seal'), ('diagram', 'Diagram/Chart'), ('figure', 'Figure/Illustration'), ('chart', 'Chart/Graph'), ('screenshot', 'Screenshot'), ('photo', 'Photograph'), ('picture', 'General Picture'), ('embedded', 'Embedded Image'), ('other', 'Other')], db_index=True, default='picture', help_text="Sub-type (only relevant when file_kind='image')", max_length=50)),
                ('file', models.FileField(help_text='The uploaded file', upload_to=attachments.models._upload_path)),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated thumbnail (images only)', null=True, upload_to='attachments/thumbnails/%Y/%m/')),
                ('file_size', models.BigIntegerField(blank=True, help_text='Bytes', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.IntegerField(blank=True, help_text='Image width in px', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Image height in px', null=True)),
                ('scope', models.CharField(choices=[('user', 'User (private)'), ('team', 'Team'), ('organization', 'Organization'), ('document', 'Document-specific')], db_index=True, default='user', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachment_files', to='documents.document')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='user_management.organization')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='user_management.team')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uploaded_by', '-created_at'], name='attachments_uploade_368c67_idx'), models.Index(fields=['organization', '-created_at'], name='attachments_organiz_b0d13a_idx'), models.Index(fields=['team', '-created_at'], name='attachments_team_id_8eb9ff_idx'), models.Index(fields=['scope', '-created_at'], name='attachments_scope_1867d8_idx'), models.Index(fields=['file_kind', '-created_at'], name='attachments_file_ki_2cc374_idx'), models.Index(fields=['organization', 'file_kind'], name='attachments_organiz_421314_idx'), models.Index(fields=['organization', 'scope'], name='attachments_organiz_2dc48f_idx')],
            },
        ),
    ]
