# Generated by Django 6.0 on 2026-01-10 07:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(help_text='ID of the content accessed', max_length=255)),
                ('access_token', models.CharField(blank=True, help_text='Token used for external access', max_length=64, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of accessor', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent')),
                ('access_type', models.CharField(choices=[('view', 'Viewed'), ('edit', 'Edited'), ('comment', 'Commented'), ('share', 'Shared'), ('download', 'Downloaded'), ('print', 'Printed'), ('export', 'Exported'), ('delete', 'Deleted'), ('restore', 'Restored')], default='view', help_text='Type of access', max_length=20)),
                ('accessed_at', models.DateTimeField(auto_now_add=True, help_text='When access occurred')),
                ('share_id', models.UUIDField(blank=True, help_text='Share ID that granted access', null=True)),
                ('session_id', models.CharField(blank=True, help_text='Session identifier for tracking', max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional access metadata (sections viewed, duration, etc.)')),
                ('success', models.BooleanField(default=True, help_text='Whether access was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if access failed')),
                ('content_type', models.ForeignKey(help_text='Type of content accessed', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who accessed (null for external/anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', '-accessed_at'], name='sharing_acc_content_575431_idx'), models.Index(fields=['user', '-accessed_at'], name='sharing_acc_user_id_cca0ec_idx'), models.Index(fields=['access_token'], name='sharing_acc_access__39ec87_idx'), models.Index(fields=['ip_address'], name='sharing_acc_ip_addr_453c4d_idx'), models.Index(fields=['access_type'], name='sharing_acc_access__67470d_idx'), models.Index(fields=['-accessed_at'], name='sharing_acc_accesse_c61868_idx')],
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(help_text='ID of the content being shared', max_length=255)),
                ('invitation_email', models.EmailField(blank=True, help_text='Email address for external invitation', max_length=254, null=True)),
                ('invitation_phone', models.CharField(blank=True, help_text='Phone number for external invitation', max_length=20, null=True)),
                ('invitation_token', models.CharField(blank=True, help_text='Unique secure token for external access', max_length=64, null=True, unique=True)),
                ('invitation_accepted', models.BooleanField(default=False, help_text='Whether external invitation has been accepted')),
                ('invitation_accepted_at', models.DateTimeField(blank=True, help_text='When invitation was accepted', null=True)),
                ('invitation_message', models.TextField(blank=True, help_text='Custom message included in invitation')),
                ('role', models.CharField(choices=[('viewer', 'Viewer - Read Only'), ('commenter', 'Commenter - Can Comment'), ('editor', 'Editor - Full Edit Access')], default='viewer', help_text='Access level granted', max_length=20)),
                ('share_type', models.CharField(choices=[('user', 'Shared with registered user'), ('team', 'Shared with team'), ('email', 'Shared via email invitation'), ('phone', 'Shared via phone invitation')], default='user', help_text='Type of share', max_length=20)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for external shares', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this share is currently active')),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='Last time content was accessed via this share', null=True)),
                ('access_count', models.IntegerField(default=0, help_text='Number of times accessed via this share')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional share-specific metadata')),
                ('content_type', models.ForeignKey(help_text='Type of content being shared (Document, File, Folder, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('shared_by', models.ForeignKey(help_text='User who created this share', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shares', to=settings.AUTH_USER_MODEL)),
                ('shared_with_team', models.ForeignKey(blank=True, help_text='Team this content is shared with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to='user_management.team')),
                ('shared_with_user', models.ForeignKey(blank=True, help_text='User this content is shared with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shared_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='sharing_sha_content_a43c51_idx'), models.Index(fields=['shared_with_user'], name='sharing_sha_shared__c99a05_idx'), models.Index(fields=['shared_with_team'], name='sharing_sha_shared__fbef02_idx'), models.Index(fields=['invitation_email'], name='sharing_sha_invitat_49c8bf_idx'), models.Index(fields=['invitation_phone'], name='sharing_sha_invitat_600f5b_idx'), models.Index(fields=['invitation_token'], name='sharing_sha_invitat_334ebf_idx'), models.Index(fields=['is_active'], name='sharing_sha_is_acti_0d064d_idx'), models.Index(fields=['shared_at'], name='sharing_sha_shared__11cc35_idx')],
            },
        ),
    ]
