# Generated by Django 6.0 on 2026-01-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_migrate_from_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='share_type',
            field=models.CharField(choices=[('user', 'Shared with registered user'), ('team', 'Shared with team'), ('email', 'Shared via email invitation'), ('phone', 'Shared via phone invitation'), ('link', 'Public shareable link (anyone with link)')], default='user', help_text='Type of share', max_length=20),
        ),
    ]
