# Generated by Django 6.0 on 2026-01-11 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sharing', '0003_alter_share_share_type'),
        ('user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(condition=models.Q(('shared_with_user__isnull', False)), fields=('content_type', 'object_id', 'shared_with_user'), name='unique_user_share'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(condition=models.Q(('shared_with_team__isnull', False)), fields=('content_type', 'object_id', 'shared_with_team'), name='unique_team_share'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(condition=models.Q(('invitation_email__isnull', False)), fields=('content_type', 'object_id', 'invitation_email'), name='unique_email_share'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(condition=models.Q(('invitation_phone__isnull', False)), fields=('content_type', 'object_id', 'invitation_phone'), name='unique_phone_share'),
        ),
    ]
