# Generated by Django 6.0 on 2026-01-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0004_add_unique_share_constraints'),
    ]

    operations = [
    ]
